### ISSUE TITLE
Getting a Power CI for Istio

### ISSUE THREAD

**Issue by gyliu513** [istio/test-infra#1118]
We want to enable Istio running on POWER, so it is better to enable POWER CI for Istio as well. 

Can anyone propose some help for how to enable this?

**Comment by linsun** [comment]
@hklai @rkpagadala I assume we don't have any power env from either circle or prow?

**Comment by hklai** [comment]
@gyliu513 @linsun could you give me better context? what is "Power CI"?
Googling just that gives me some interesting but apparently unrelated results .=)

**Comment by gyliu513** [comment]
@hklai here what I mean `POWER CI` is that I want to enable the CI can also run on [IBM POWER Systems](https://www.ibm.com/it-infrastructure/power).

You may saw that Kubernetes already support releasing POWER (ppc64le) and s390x docker images at https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#server-binaries , I hope that istio can also support those platforms so as to enlarge Istio eco-system, comments?

FYI @morvencao @clyang82 @zxdiscovery

**Comment by hklai** [comment]
I suspect someone needs to provision resources on POWER and make CI work with it? I doubt both Prow and circle can manage it, but I am less certain about the latter.

**Comment by howardjohn** [comment]
Istio project has no plans to support alternative CI systems.
