### ISSUE TITLE
gke test cluster lacks trace.append permission

### ISSUE THREAD

**Issue by bianpengyuan** [istio/test-infra#1183]
Stackdriver e2e test requires the test gke cluster to have trace append permission, and https://github.com/istio/test-infra/pull/1180 attempts to add that. However tracing test is still consistently failing due to lack of permission scope: https://testgrid.k8s.io/istio-release#e2e-stackdriver.

@utka @douglas-reid

**Comment by icygalz** [comment]
the cluster has the appropriate permission and the test is passing now! Closing the issue :).

**Comment by bianpengyuan** [comment]
@icygalz Nice, thanks!
