### ISSUE TITLE
Require Release Owner approval for PRs going to release branch after release is published

### ISSUE THREAD

**Issue by utka** [istio/test-infra#1198]
After release is cut and published for every PR which is going into release branch we need to make sure that PRs are approved by Release Manager on top of OWNERS approval

**Comment by howardjohn** [comment]
Just a comment - this will be much better than having admin override the merge, since when we override the tests don't rebase and run again so failures can (have) slipped in

**Comment by howardjohn** [comment]
If we can't do this easily in prow, a hack that could work is having an `Admin Approved` label that is required. But I don't think we can lock users from setting it themselves

**Comment by fejta** [comment]
/assign @howardjohn @geeknoid 

Isn't this done or at least doneish?

**Comment by howardjohn** [comment]
This is done
