### ISSUE TITLE
go get mason_client is timing out 

### ISSUE THREAD

**Issue by utka** [istio/test-infra#1199]
As example 
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/13054/e2e-simpleTests-cni/2508/build-log.txt
We need to add the RUN go get istio.io/test-infra/boskos/cmd/mason_client to the dockerfile that creates the image or use go mod vendor all your dependencies and then bazel build //vendor/istio.io/test-infra/boskos/cmd/mason_client
Example: https://github.com/kubernetes/test-infra/blob/master/hack/update-deps.sh

**Comment by howardjohn** [comment]
Should be fixed by goproxy
