### ISSUE TITLE
Codecov requires to more code to be covered when some code is deleted

### ISSUE THREAD

**Issue by incfly** [istio/test-infra#1204]
If a PR simply delete some code that was previously guarded by unit test, that file code coverage will drops. `a - 20 / b - 20 < a / b`. The code coverage percentage drops. Deveoper has two options.

- Write more unit test that he didn't touches in that PR.
- Changes requirements files for that file.

First option is not ideal to ask developers write code beyond the context of the PR. Ideally we can avoid this situation by a better calculation of the code coverage metrics.

**Comment by incfly** [comment]
https://github.com/istio/istio/pull/10830#issuecomment-480660849

**Comment by howardjohn** [comment]
We don't have codecov on presubmit so its not really accurate anymore

**Comment by clarketm** [comment]
> We don't have codecov on presubmit so its not really accurate anymore

@howardjohn 
I was merely verifying https://github.com/istio/bots/pull/126 was deployed properly and works as intended in production (i.e. Github reopen events invalidate the staleness delta).
