### ISSUE TITLE
Setup a new prow cluster to run CircleCI tests on KIND.

### ISSUE THREAD

**Issue by icygalz** [istio/test-infra#1206]
Setup a new prow cluster to run KIND tests for tests cases that is now running on CircleCI.

**Comment by icygalz** [comment]
prow is not designed to have 2 different prow clusters running on the same repo. What we can do is that we will create a workload cluster and run kind test on that workload cluster. The kind tests will still be triggered by current existing prow cluster

**Comment by howardjohn** [comment]
We have already moved all our circleci tests to prow and have kind running

/close
