### ISSUE TITLE
Gubernator has been deprecated. Use Spyglass instead.

### ISSUE THREAD

**Issue by icygalz** [istio/test-infra#1239]

**Comment by fejta** [comment]
For more details on prow's built-in log viewer and its extensibility features please see https://github.com/kubernetes/test-infra/tree/master/prow/spyglass

PR to migrate is out for review (#1438) 

Sent FYI to DL: https://discuss.istio.io/t/view-pending-job-logs-directly-in-prow/3023

URLs
* New: https://prow.istio.io/view/gcs/istio-prow/logs/release-requests-janitor/9398
* Old: https://gubernator.k8s.io/build/istio-prow/logs/release-requests-janitor/9398

**Comment by krzyzacy** [comment]
/cc

will try to make spyglass the default viewer

**Comment by fejta** [comment]
@krzyzacy I think this one is already done unfortunately. See #1438

**Comment by fejta** [comment]
Seems live:

* New jobs runs use the spyglass URL (example: https://github.com/istio/test-infra/pull/1447)
* Sent notice to https://discuss.istio.io/t/view-pending-job-logs-directly-in-prow/3023/2

/close
