### ISSUE TITLE
/retest message is wrong

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1254]
PRs say "The following tests failed, say /retest to rerun them all:"

But the command is `/test all` (retest plugin isnt enabled?

This is defined here https://github.com/kubernetes/test-infra/blob/master/prow/github/report/report.go#L289

but can't find it in this repo...

This is very confusing for new users

**Comment by icygalz** [comment]
The message sounds right to me.
/retest will only rerun all failing tests..
/test all -> will run all tests whether they are passing or failing..
/retest plugin in enabled.
Any recommendation on what might be clearer sounding?

**Comment by howardjohn** [comment]
I thought `/retest` doesn't work? Maybe I am wrong though, I will try it out and close this if so

**Comment by howardjohn** [comment]
I think I was impatient :slightly_smiling_face: seems to work
