### ISSUE TITLE
Create script to generate test grid config

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1348]
We have our test grid go out of sync all of the time, some tests are missing, etc. 

We should look into making a script that will take our prow config and generate test grid config

**Comment by howardjohn** [comment]
I think this can be done automagically by prow now. See https://github.com/kubernetes/test-infra/blob/master/testgrid/config.md#prow-job-configuration

**Comment by fejta** [comment]
Is this maybe done? Or at least partially done? I see testgrid annotations in the prow jobs

**Comment by howardjohn** [comment]
This is done now
