### ISSUE TITLE
Prevent code coverage regression for given packages

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#135]
Background:
In a previous system (proprietary, not OSS), we had a list of packages with their baseline coverage and perf numbers. Checkins were not allowed to enter the repo if these numbers regressed. Developers could change the baselines at will in the case a regression was inevitable. So the point was not to prevent forward progress, it was more to prevent accidental regressions. We also had a process that would regularly increase any coverage or perf numbers based on observed current levels. So the numbers would naturally tend to get better over time and never backslide.

So imagine just having a file at the top of the repo that lists the various packages and their coverage numbers. As part of the checking process, we run a little script that compares the output of the coverage test run with what's in the file, and then fails the commit if there's a regression.

-----
In every repo we could have a codecov.info file which defines the threshold and we could have the script in the toolbox repo such that all modules can use it.

**Comment by ijsnellf** [comment]
@sebastienvas: Can we perhaps exclude integration tests from this check? I added tests to the `istio.io/manager/test/integration` package, which resulted in a net decrease in overall coverage according to codecov even though I was actually making our tests more complete.

**Comment by yutongz** [comment]
@ijsnellf  I am not sure if you should do that, it really depends on the tests you added. But you can change the threshold to at lease make your change pass Jenkins tests anyway.

**Comment by yutongz** [comment]
Fixed
