### ISSUE TITLE
Deploy Velodrome for Istio

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#14]
This will help us understand where we need to focus our efforts:
https://github.com/kubernetes/test-infra/tree/master/velodrome/

**Comment by sebastienvas** [comment]
Talked to @apelisse about this. We don't need to have our own deployement. He is gonna set it up for Istio repos. We'll then be able to set the metrics that we want.

**Comment by sebastienvas** [comment]
Velodrome is deployed on 130.211.224.127. We need to add velodrome.istio.io.

**Comment by sebastienvas** [comment]
Thanks @apelisse. Velodrome is up and running at velodrome.istio.io

**Comment by kyessenov** [comment]
Cool!
