### ISSUE TITLE
Prow job names should be unique

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1402]
I cannot run `mkpj --config-path config.yaml --job istio-kind-simpleTest-master --job-config-path cluster/jobs/istio/istio | phaino` because the job is defined in two places, master and prow-staging. It doesn't crash, but it does uses the prow-staging config

See also https://github.com/kubernetes/test-infra/issues/13280

**Comment by fejta** [comment]
Yes please, and I would also recommend eliminating the context: field and just using the job name (default)

Aside: piping to phaino doesn't work super great as it will ask you to input the location of various volumes and secrets.

Instead I would recommend something like 
```console
$  mkpj --job=build-test --config-path prow/config.yaml --job-config-path prow/cluster/jobs > ~/test.yaml && phaino ~/test.yaml
```

**Comment by howardjohn** [comment]
This is done
