### ISSUE TITLE
Consider using run_if_changed

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1407]
Docs here: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md

We can selectively run tests on only certain changes

Its not immediately obvious which changes required which tests -- we may have unexpected dependencies between components, so we should be cautious and not just blanket  run X tests for changes to `X/`

initial thinking was to disable tests for changes to just simple things like `*.md` but it doesn't like there are many commits that are just touching READMEs

**Comment by howardjohn** [comment]
Also it seems intended for selectively enabling tests (run pilot tests if you change pilot) rather than selectively disabling tests (don't run tests if you don't change things other than md) so we may be better suited to approach it this way.

Some inspiration can be found with https://github.com/kubernetes/test-infra/search?p=2&q=run_if_changed&unscoped_q=run_if_changed

**Comment by fejta** [comment]
run_if_changed is great. Highly recommend taking advantage of it. It now works with postsubmits too, which you can use to do some CD-type workflows

**Comment by fejta** [comment]
Pretty sure this pattern is now understood here
