### ISSUE TITLE
Weird behavior with multiple tests runs

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1413]
https://gubernator.k8s.io/builds/istio-prow/pr-logs/pull/istio_istio/15259/istio-lint-master/

Ive seen this on other ones too - there is a bunch of reported test runs for no apparent reason. I don't think all of these correlates to an actual pod being run though, but haven't investigated much

@fejta

**Comment by howardjohn** [comment]
Looking at the ProwJobs it seems only the ones that are pass/fail have prowjobs, no clue where the other ones came from

**Comment by fejta** [comment]
It is quite possible the pod was unable to complete for some reason -- evicted, OOMd, etc. Prow detects when kubernetes does not complete running the pod and reschedules it

**Comment by howardjohn** [comment]
Seems likely the cause, the lint ones were running OOM

**Comment by howardjohn** [comment]
confirmed this is due to OOM, we should get rid of our highcpu instances probably -- a lot of our tests use a lot of memory. Will also increase memory requqests
