### ISSUE TITLE
e2e-simpleTests-distroless-master not running

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1418]
This is a new test we added fairly recently: https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/istio/istio.istio.master.yaml#L445-L459

It seems it never actually runs: https://prow.istio.io/?job=e2e-simpleTests-distroless-master

Looking at the cluster there are no prowjobs even created

**Comment by c0d1ngm0nk3y** [comment]
@utka , do you have any idea, how to enable these tests?

**Comment by utka** [comment]
Config in prow cluster looks correct and has info about distroless test, but in logs there is no info about the test being triggered. Looking into it more.

**Comment by utka** [comment]
Actually, the config misses "always_run: true" option, I will add it now.

**Comment by fejta** [comment]
https://github.com/istio/test-infra/blob/45aed557365a59e1a77bf03aef88ac7c87ec6b40/prow/cluster/jobs/istio/istio/istio.istio.master.yaml#L2122

/close
