### ISSUE TITLE
Use peribolos to manage org memberships and teams

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1425]
See https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos and https://github.com/kubernetes/org

We should declare what members we want to have at what levels. This also allows us to define teams, etc.

**Comment by howardjohn** [comment]
@linsun @geeknoid @duderino this could help with some of the issues we were discussing last week regarding maintainers auditing/management

**Comment by howardjohn** [comment]
@geeknoid did you ever look into this? As we use teams a lot more now it may be useful

**Comment by geeknoid** [comment]
Yes, I looked into this and at this point I'm not particularly interested. I'd rather use the GitHub UI for this stuff.

**Comment by howardjohn** [comment]
I'm curious why? This seems like a fantastic tool. I would much rather have our config as code rather than UI

**Comment by geeknoid** [comment]
A giant yaml file with thousands of lines is not my idea of fun.

To add a user right now, I follow the GitHub flow. I add them to the org, pick a team, they get an invitation and they're in. The GitHub UI provides hints to make sure I'm selecting only valid names to enter in the org and in teams. Etc.

**Comment by fejta** [comment]
If your organization takes thousands of lines to declare, then this is not something you can remember in your head. You should write it down somewhere.

**Comment by howardjohn** [comment]
I am a little confused by the dry run of peribolos. The docs here show a bunch of stuff happening: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos#initial-seed

But if I run `peribolos --config-path org/istio.yaml` from https://github.com/istio/community/pull/253 I see
```
{"client":"github","component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100)","time":"2019-12-20T13:30:58-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:204","func":"main.main","level":"info","msg":"Finished syncing configuration.","time":"2019-12-20T13:30:58-08:00"}
```

If I change the file to prefix with 
```
org:
  istio:
    ....
```

it does more but looks like everything is skipped:
```
{"client":"github","component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100)","time":"2019-12-20T13:31:28-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:851","func":"main.configureOrg","level":"info","msg":"Skipping org metadata configuration","time":"2019-12-20T13:31:28-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:863","func":"main.configureOrg","level":"info","msg":"Skipping org member configuration","time":"2019-12-20T13:31:28-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:870","func":"main.configureOrg","level":"info","msg":"Skipping org repositories configuration","time":"2019-12-20T13:31:28-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:876","func":"main.configureOrg","level":"info","msg":"Skipping team and team member configuration","time":"2019-12-20T13:31:28-08:00"}
{"component":"peribolos","file":"/usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/test-infra@v0.0.0-20191205222449-22a361b017ee/prow/cmd/peribolos/main.go:204","func":"main.main","level":"info","msg":"Finished syncing configuration.","time":"2019-12-20T13:31:28-08:00"}
```

So I am not quite sure what is going wrong here

**Comment by howardjohn** [comment]
@fejta any advice on the above?

**Comment by howardjohn** [comment]
This is done
