### ISSUE TITLE
Use commenter to automate common tasks

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1431]
See https://github.com/kubernetes/test-infra/tree/master/robots/commenter and https://testgrid.k8s.io/sig-testing-fejtabot

We use this to do things like:
* Ping repos that need to create a SECURITY_CONTACTS file
* Close stale issues
* /retest approved and flaking PRs, etc.

Example of such a job: https://github.com/kubernetes/test-infra/blob/ccfbc528adc48bf31f966ea5cb80248296093230/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml#L3-L43

**Comment by howardjohn** [comment]
@geeknoid is working on some stuff that may have some overlap at https://github.com/istio/bots. I am not sure the current state of it or how much overlap there would be here though
