### ISSUE TITLE
Convert linter job to bazel, run on RBE

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1437]
This script already requires bazel: https://github.com/istio/test-infra/blob/c553920d22899da68810a21b758daa4e266899dc/scripts/linters.sh#L29

So let's move all this logic (golangcilint, check_licenses, buildifier, etc) into bazel test rules that we can run remotely on RBE, like we do for kubernetes/test-infra, for example: https://github.com/kubernetes/test-infra/blob/d639b34274a4a636df8a3c6ee0637319f72aa659/hack/BUILD.bazel#L315-L324

**Comment by howardjohn** [comment]
Closing as our linter does not use bazel now
