### ISSUE TITLE
Jobs results previously uploaded to the wrong place.

### ISSUE THREAD

**Issue by cjwagner** [istio/test-infra#1450]
Up until the recent Prow changes to enable spyglass, Prow and the [custom bootstrap image variant](https://github.com/istio/test-infra/tree/master/docker/prowbazel) were configured to upload/expect uploads at the wrong GCS location.  In particular, the highest directory level was omitted so presubmit results went to `gs://istio-prow/pull/org_repo/pr-num/job-name/build-id/` instead of `gs://istio-prow/pr-logs/pull/org_repo/pr-num/job-name/build-id/` and postsubmit/periodic results went to `gs://istio-prow/job-name/build-id/` instead of `gs://istio-prow/logs/job-name/build-id/`.

Documentation of correct layout: https://github.com/kubernetes/test-infra/tree/master/gubernator#gcs-bucket-layout
Actual upload location prefix: (should be postfixed with `pr-logs` or `logs` [examples](https://github.com/kubernetes/test-infra/search?q=--upload%3Dgs%3A%2F%2F&unscoped_q=--upload%3Dgs%3A%2F%2F)) 
https://github.com/istio/test-infra/blob/93a08e716e9c65e5a0ad194ff2ca03328a709b97/docker/prowbazel/entrypoint#L27
Previously expected upload location: (note the lack of `pr-logs` or `logs`)
https://github.com/istio/test-infra/blob/c0f75e219e04daf27b0369b101633415a479b69a/prow/config.yaml#L6

Currently expected upload location: (and the correct location according to pod-utils and other tools)
https://github.com/istio/test-infra/blob/52bb7a801d162a9b41ee5461e0ed7187eacfab4c/prow/config.yaml#L3

The TestGrid config appears to assume the correct location, but somehow most of the configured dashboard don't seem to have problems.
https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L934-L1439

I do see that some jobs upload to the right place (or did at some time) so this could be a problem with just this image, but based on the old job_url_template value I suspect this is widespread.

/assign @fejta @utka

**Comment by fejta** [comment]
I think we should fix this by asking people with misconfigured jobs to:
1) Log an issue to update to pod-utils
2) Update the job_url_template to special case their job while they migrate to pod-utils.

**Comment by utka** [comment]
It generates upload link https://github.com/istio/test-infra/blob/6e80fedf3d511148de22428f2d3522b77d2701e8/docker/istio_builders/prow_builder/bootstrap/bootstrap.py#L912

**Comment by utka** [comment]
Can someone give example what does update to pod-utils looks like ?

**Comment by bianpengyuan** [comment]
Any updates on this issue? Prow is blocking changes to be merged in istio/proxy and re-triggering the tasks does not help... so this is a bit urgent I guess. For example: https://github.com/istio/proxy/pull/2297.

**Comment by cjwagner** [comment]
> Can someone give example what does update to pod-utils looks like ?

Any job that specifies `decorate: true` is using the pod utils. All the jobs here for example: https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml
For more examples check out the jobs for `k/t-i` that specify `decorate: true`: https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes/test-infra

Here are the docs for using pod utilities: https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#writing-a-prowjob-that-uses-pod-utilities

cc @krzyzacy

**Comment by fejta** [comment]
@bianpengyuan if there are istio/proxy tests that upload to the wrong location then someone involved with that repo needs to do one of the following:
* fix the jobs to upload to the right location: https://github.com/istio/test-infra/tree/master/prow/cluster/jobs/istio/proxy
  - Start using pod utils, stop relying on the deprecated and forked bootstrap library to upload results
  - Fix the bootstrap library to upload to the correct location
* teach prow's job_url_template to special case the URLs for those jobs: https://github.com/istio/test-infra/blob/9f4c60824b9537b5db679baee2bff917ef12a1e2/prow/config.yaml#L3

**Comment by fejta** [comment]
Please resolve any remaining instances of jobs uploading to the right place by making them upload toe the right place:
a) Migrate them to podutils
b) Change the logic in the test container to upload to the correct location
