### ISSUE TITLE
Remove custom context from prow jobs

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1460]
Right now we have configs like

```
  - name: integ-framework-local-presubmit-tests-master
    context: prow/integ-framework-local-presubmit-tests.sh
```

Not sure what purpose this has but it has caused confusion. Especially for the ones like above -- ` prow/integ-framework-local-presubmit-tests.sh` isn't even a real file!

If we just remove the context it will default to the job name which I think makes sense.

WDYT @utka @icygalz

**Comment by howardjohn** [comment]
@cjwagner is this safe to do once we have https://github.com/kubernetes/test-infra/tree/master/prow/cmd/status-reconciler#status-reconciler deployed?

**Comment by cjwagner** [comment]
Yes, and +1 for just using the job name as the context. That is what we do for prow.k8s.io.

**Comment by howardjohn** [comment]
Thanks! Can you let me know what work would need to be done to have a status-reconciler deployment? Or is that part of the prow upgrades you guys have been working on?

**Comment by cjwagner** [comment]
> Thanks! Can you let me know what work would need to be done to have a status-reconciler deployment? Or is that part of the prow upgrades you guys have been working on?

It is on the list of things to do. https://github.com/istio/test-infra/issues/1396
I don't think there are any blockers to deploying it now. Someone just has to add a deployment file like [this one](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/statusreconciler_deployment.yaml) with the arguments tweaked for Istio and update the [Makefile](https://github.com/kubernetes/test-infra/blob/master/prow/Makefile).

**Comment by clarketm** [comment]
status-reconciler deployed in: #1481

**Comment by howardjohn** [comment]
This is 90% done, just a few repos left

**Comment by howardjohn** [comment]
Done for everything
