### ISSUE TITLE
Unit tests run 2x slower in prow than circleci

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1461]
Circle test, runs in 13min: https://circleci.com/gh/istio/istio/452452
Prow test, runs in 24min: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15455/istio-unit-tests-master/3408. History shows this is common: https://prow.istio.io/?job=istio-unit-tests-master

I greped through the logs of both of those runs for "ok  " getting the timings go gave for individual packets. Circleci totals at 7:30, prow at 9:30. So the difference go is reporting for individual tests is pretty similar -- we are losing most of the time somewhere else. Just to make sure go isn't reporting these wrong, I did the same greping but looking at individual tests (PASS: ...) instead of the summaries and get: Circle: 8:40, Prow: 10:50

One difference I see in the tests is in prow we run `make build`. This takes ~2mins.

The tests just running a couple minutes slower + the 2 minutes to build should put prow at 17min, so I am not sure why they are taking 24min. It is hard to tell from the logs since they don't have many timestamps on them.

I think `kubectl log` can give timestamps, so maybe we should look there next

**Comment by sdake** [comment]
the git clone  may take a little extra time as well.  IIRC circleci keeps a copy of the git repo around in a cache of containers for a particular repo on our particular plan.

**Comment by howardjohn** [comment]
My understanding is the clone happens in an init container so that would not be included in the test time, not certain though. Prow is also doing the rebasing logic though so I bet that part is a bit slower, I haven't look at how long it takes though.

**Comment by fejta** [comment]
https://prow.istio.io/?job=istio-unit-tests-master&state=success so it seems to be reliabily taking 25-50m right now when it passes, we should debug this.

/assign

**Comment by fejta** [comment]
Resolved as a node issue, right?

**Comment by howardjohn** [comment]
Yep, this is resolved. Not sure exactly what our current tests in circle would finish in now, but our tests are performing well now
