### ISSUE TITLE
Tests not getting reported to github

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1501]
We have been seeing a number of tests without status being reported lately. One example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-racetest-master/1861. The test is failed but the PR shows the test as running still: https://github.com/istio/istio/pull/15501. Another one where I think all of these are done but are still marked as running: https://github.com/istio/istio/pull/15589. `finished.json` is uploaded. Any idea what can cause this or where we can look to debug further?

Istio is not using crier

The ProwJob is marked as succeeded

/assign @Katharine

**Comment by fejta** [comment]
Suspect this is related to running out of tokens due to other tools sharing the account and not using ghproxy

Please reactivate if we see this again.
/close
