### ISSUE TITLE
Does anyone use zenhub in istio/test-infra?

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1503]
/assign

If not then I intend to delete the https://webhook.zenhub.io/webhook/github/v1/53...cc webhook defined for this repo

**Comment by howardjohn** [comment]
I don't know that anyone uses it in this repo but definitely in istio/istio

**Comment by fejta** [comment]
If we like it then I'd recommend installing it at the org level, and deleting it here regardless.

**Comment by geeknoid** [comment]
ZenHub is a GitHub app. It creates these web  hooks automatically. So you may  delete it, but it'll come back once ZenHub decides it needs it.
