### ISSUE TITLE
Enable tide on all repos

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1520]
/assign @fejta @geeknoid 

@sdake @howardjohn 

Basic intent is to create CODEOWNERS files in all repos and then configure tide to search for `review:approved` issues, which is something Martin is working on and will canary on istio.io or operator.

Right now tide is configured to look for lgtm, approved labels instead, which work with OWNERS files. If a repo has these OWNERS files (istio/istio, istio/test-infra do, for example), then you can turn on tide now and auto-migrate later with the following:

* Ensure the `lgtm` and `approve` plugin are turned on at either the org (`istio`) or repo (`istio/istio`) level
  * org - https://github.com/istio/test-infra/blob/4b57822c8150b91ed404adbdd16714c6850d9313/prow/plugins.yaml#L63-L67
  * repo https://github.com/istio/test-infra/blob/4b57822c8150b91ed404adbdd16714c6850d9313/prow/plugins.yaml#L79-L85
* Configure the `lgtm` plugin to treat a github approve like an `/lgtm` comment
  * This is optional but necessary in order to have github approve add the lgtm label, otherwise you need an `/lgtm` comment.
  * https://github.com/istio/test-infra/blob/4b57822c8150b91ed404adbdd16714c6850d9313/prow/plugins.yaml#L37-L50
* Configure `tide` to respond to the repo:
  * https://github.com/istio/test-infra/blob/4b57822c8150b91ed404adbdd16714c6850d9313/prow/config.yaml#L191-L201
* Disable mergify on the repo

Repos configured this way can start using tide now and will get auto-upgraded to use CODEOWNERS instead of OWNERS.

Alternatively continue using mergify and just wait for us to validate the new tide pattern and turn this on for all repo.

**Comment by sdake** [comment]
@fejta 

For repos already on mergify and CODEOWNERS (going to canary on operator repo instead of istio.io as istio.io needs backport featrues of mergify atm):

1. why `blunderbuss` in plugins.yaml?
1. why `approve` in pluginsl.yaml?
1. why `verify-owners` in plugins.yaml?

The rest makes sense.

Cheers
-steve

**Comment by fejta** [comment]
Yes, it is quite possible that the `reviewApprovedRequired: true` tide config option will make `blunderbuss` `approve` and `verify-owners` unnecessary.
