### ISSUE TITLE
remove need for path hacks for test-infra for tide/CODEOWNERS transitions

### ISSUE THREAD

**Issue by sdake** [istio/test-infra#1523]
Path hacks are needed for anything that executes code in $GOPATH/bin.  This is effectively every repository in Istio.

See makefile in istio/operator:

```
	# These PATH hacks are temporary until prow properly sets its paths
	@PATH=${PATH}:${GOPATH}/bin scripts/run_mandiff.sh
```

temporary becomes permanent in our world :)

**Comment by howardjohn** [comment]
You just need to add this to the $PATH in the builder image as far as I know

**Comment by clarketm** [comment]
Closing as `GOPATH=/go` now in build-tools image.
