### ISSUE TITLE
racetests take 2x longer on prow

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1524]
Circle finishes in 20min: https://circleci.com/gh/istio/istio/451639

prow finishes in ~40min: https://prow.istio.io/?job=*racetest*. This is after I have optimized the race tests a bit already, before it was around 50min

**Comment by fejta** [comment]
We traced this down to the node issue, right?

**Comment by howardjohn** [comment]
Part node issue, part just slower in general. I am pretty sure the "slower in general" is due to having 5 CPU vs 8 CPU on circleci. When the nodes were cycled this was running about 28 mins vs 20 min in circleci. So fairly close
