### ISSUE TITLE
Remove bazel usage from the repo

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1580]
No other repo in istio uses bazel. As far as I know there is no reason we need bazel here, and it makes the repo unfamiliar for Istio contributors.

If possible we should remove bazel.

I am not familiar enough with bazel to know how feasible this is and if its as simple as `rm all_bazel_stuff` and replace `bazel test` with `go test`, etc

**Comment by clarketm** [comment]
@howardjohn - I can help with this. Depending on the particular `bazel` rule we can translate to the equivalent, underlying command (e.g. `go_test(...)` -> `go test ...`). Is the desire to replace `bazel` with `make` for everything: *building*, *testing*, *running* or just testing?

**Comment by clarketm** [comment]
@sebastienvas @fejta 

Since #1631, it would appear `bazel` no longer works yet there are still artifacts (i.e. subprojects with`BUILD.bazel` files like `boskos`) in the repo that depend on it. 

It would be nice to come to a compromise of *if* or *to what extent* we want to use `bazel` in the `istio/test-infra` repo. At the very least, we should keep it in a *healthy* state for the components that depend on it.

**Comment by howardjohn** [comment]
That is exactly why I created https://github.com/istio/test-infra/pull/1635, to remove the BUILD.bazel files as they are actively misleading. This change was blocked.

**Comment by duderino** [comment]
> No other repo in istio uses bazel. 

istio/proxy does, but it's still OK to remove bazel from istio/test-infra.  But let's definitely not remove bazel from istio/proxy ;)

**Comment by sebastienvas** [comment]
Bazel was used for 2 + years and nobody complained.

I find it really sad. the time gained when working with docker images, and daily workflows for me is priceless. Anyways I am doing one or two contribution a month to fix stuff, so I may not be the standard user. I think @fejta has made some bazel contrib in the last months so He may have more context.

**Comment by fejta** [comment]
I am opposed to removing bazel usage from this repo

**Comment by howardjohn** [comment]
Given https://github.com/kubernetes/kubernetes/pull/99561 this seems to be where upstream is moving? Unless k/test-infra will still use bazel

**Comment by BenTheElder** [comment]
That KEP expressly covers _only_ github.com/kubernetes/kubernetes. Sub-projects will continue to use their preferred tools. I don't think there's currently a movement to change any other repos.

**Comment by howardjohn** [comment]
Ack, thanks Ben.
