### ISSUE TITLE
Cherry pick missed

### ISSUE THREAD

**Issue by geeknoid** [istio/test-infra#1598]
This PR wanted to be cherry picked to master, yet it didn't happen:

https://github.com/istio/istio.io/pull/4753

Other PRs filed within minutes in the same repo did get automatically cherry picked, so the cherry picker is generally working. The one difference is that this PR was trying  to cherry pick from release-1.2 to master, while the others are going from master to release-1.2.

**Comment by fejta** [comment]
/unassign @fejta @cjwagner 
/assign @geeknoid 

Please confirm that the webhook was delivered to the external plugin, which we do not have access to

**Comment by geeknoid** [comment]
I did a "/cherrypick master", which triggered the cherry pick to happen.

**Comment by geeknoid** [comment]
The  logs for the cherrypicker workload show 3 entries @ 12:18 today, related to the PR in question. I can't divine anything from these logs.

**Comment by geeknoid** [comment]
As shown in the screen shot, GitHub thinks it delivered all the  necessary  events successfully.

<img width="910" alt="Screen Shot 2019-08-05 at 14 18 58" src="https://user-images.githubusercontent.com/22780957/62495852-03e2a400-b78c-11e9-8f67-511f00f2de0d.png">

**Comment by clarketm** [comment]
Were we ever able to identify the cause of the missed cherrypick or has there been any reoccurrence of this issue since? 

😞 The logs are no longer retained for the affected time range of the *original* report.

**Comment by clarketm** [comment]
closing as duplicate of: https://github.com/istio/test-infra/issues/2309
