### ISSUE TITLE
Report test failures to slack

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1643]
We current send test failures to google group istio-oncall, but I don't think many look at this. I don't think testgrid supports slack, but we can set up the slack Email app to get an email that will forward to slack, where it will get noticed

We have many daily releases and no one notices

**Comment by howardjohn** [comment]
/assign @geeknoid 

I'll set up the testgrid part if you do the rest (or I can, but I doubt I have permission) and get an email we send the alert to

**Comment by scottilee** [comment]
@geeknoid here are the directions for Slack email: https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack#set-up-a-forwarding-email-address

**Comment by geeknoid** [comment]
I totally missed this issue... We already have the necessary things setup I think. If you manually push something into the test-infra repo, a post appears a second later on Slack. See the "slack" stanza in plugins.yaml which controls this. This seems like a fairly-specific use case, but it shows that the Slack-side config is sufficient.

**Comment by geeknoid** [comment]
We should also report the publication of new build-tools container images if that's possible...

**Comment by howardjohn** [comment]
Oh interesting, prow can do it directly without going through testgrid
hacks. Nice

**Comment by scottilee** [comment]
Good news, there is https://github.com/kubernetes/test-infra/blob/master/prow/cmd/crier/README.md#slack-reporter. I will try to implement this soon.

**Comment by scottilee** [comment]
I apologize about the delay on this. I opened a PR here: https://github.com/istio/test-infra/pull/1871.
