### ISSUE TITLE
Create a dedicate build cluster

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1670]
I thought there was another issue for this, but I can't find it. 

Currently we run our tests in the same cluster as prow runs. This is a security issue, and makes it so that changes we make in the build cluster can impact the prow infra, etc etc.

We should create a second cluster that will run our jobs and has minimal permissions possible

**Comment by howardjohn** [comment]
I see the docs here: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#run-test-pods-in-different-clusters

But they aren't clear enough to me to actually do this myself.. not sure where to put that config? 

It looks like k8s has a cluster 'test-infra-trusted' but doing a grep for that doesn't actually show where the cluster is configured.

**Comment by clarketm** [comment]
@howardjohn - there is a reference to adding a separate build cluster https://github.com/istio/test-infra/issues/1396#issue-462905287 but no dedicated issue that I am aware of. 

I am actively working on getting a **build / test** cluster setup for Istio. I began provisioning the resources for the node pools yesterday. `test-infra-trusted` is actually the primary k8s-prow service cluster.

**Comment by howardjohn** [comment]
Nice! thanks @clarketm . Is the cluster in istio-testing project still?

**Comment by clarketm** [comment]
For isolation and organization, I am creating the cluster in a separate project `istio-prow-build`. Once the cluster is running, I will ensure IAM roles are delegated appropriately to the team and then we can plan the (incremental) migration of the jobs.

**Comment by howardjohn** [comment]
@clarketm I was hoping to get some bigger nodes so our tests can run faster/less flaky. Should I just wait for this to do that? We currently run 8cpu nodes with 5core limit, I want at least 8 core limits, as our tests are pretty throttled right now

**Comment by clarketm** [comment]
@howardjohn - I am using the current resource allocations from the default (`istio-testing`) prow cluster build/test pools as the starting point.

![image](https://user-images.githubusercontent.com/9957358/63404519-6b0d7480-c398-11e9-9c1e-5113b351819f.png)

If you have any specific tweak to this please provide them *now*. If possible, provide **all** node spec details you wish to customize for *both* the `build-pool` (`ssd-build-pool-2`) and `test-pool` (`test-pool-1`).

**e.g.**
![image](https://user-images.githubusercontent.com/9957358/63404876-aeb4ae00-c399-11e9-91f4-469a55fd5804.png)

**Comment by clarketm** [comment]
Build cluster now active.
/close

**Comment by clarketm** [comment]
https://github.com/istio/test-infra/pull/1721, https://github.com/istio/test-infra/pull/1722
