### ISSUE TITLE
CODEOWNERS files don't allow owners that don't receive notifications.

### ISSUE THREAD

**Issue by cjwagner** [istio/test-infra#1694]
Since replacing OWNERS files with the CODEOWNERS file I have been receiving lots of GH notifications that aren't relevant to me. I think I can prevent the spam by removing myself from the CODEOWNERS for `*` and `/prow/config/`, and adding myself for `/prow/cluster/`, but even then I still won't be able to make changes to jobs under `/prow/cluster/jobs/` which is needed for various maintenance operations (including Prow bumps once the k8s cron jobs are switched to ProwJobs).

Based on this thread there is no way to work around this with CODEOWNERS files:
https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNER-Required-Reviews/td-p/1128/page/2
OWNERS files address this problem by distinguishing `approvers` from `reviewers`.

Have others been encountering this deficiency in CODEOWNERS files and if so, how have they addressed it?

**Comment by cjwagner** [comment]
Adjusting CODEOWNERS file: #1695

**Comment by kyessenov** [comment]
I just get a lot more personally addressed emails from github. I haven't quite figured out an email filter for that.
