### ISSUE TITLE
Allow testing of job changes before changes are committed

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1734]
Right now it is pretty hard to test changes to jobs. We can test locally with a variety of tools like mkpj, mkpod, phaino, etc, but this is tedious and only gives an approximation of what will run. Using mkpod and running in a GKE cluster is pretty close, but even with this its pretty challenging to run all of the jobs since we have so many.

Ideally when the jobs are changed, the new jobs would run in the PR. The only way I can think of achieving this is https://github.com/kubernetes/test-infra/issues/13370, so this issue may just be essentially tracking that.

**Comment by howardjohn** [comment]
One example where this would be super useful - upgrading golang version. This could break basically any test in some subtle way, so I have no choice but to run a bunch of tests locally (will take hours) or push it out and hope for the best.

**Comment by howardjohn** [comment]
Another case where we wasted a few hours as a result of this https://github.com/istio/istio/pull/16428

**Comment by geeknoid** [comment]
I just wasted a few hours today trying to debug why a PR in istio/istio wasn't working right. Problem is the fact the CI system was configured to using an older version of our linter, as compared to what I was trying to use in my PR. I really wish the CI system's config were co-located in the repo to make this kind of thing harder to screw up.

**Comment by howardjohn** [comment]
Changes like this are impossible to do "right" since they require atomic changes between test-infra and all of our other repos: https://github.com/istio/istio/pull/17797

**Comment by howardjohn** [comment]
Spent a while debugging differences  in local runs and CI in istio/operator today, could have been avoided if we had this

**Comment by sdake** [comment]
> Spent a while debugging differences in local runs and CI in istio/operator today, could have been avoided if we had this

PR in question where lack of atomicity resulted in lost engineering productivity: https://github.com/istio/operator/pull/477

**Comment by howardjohn** [comment]
We had an engineer go through the tools -> common files -> test-infra cycle 3 times because they ran into issues that would not exist if we did this. Granted they should have tested locally, but still would be really nice to not have to jump through hoops

**Comment by howardjohn** [comment]
Another example of this - https://github.com/istio/istio/pull/19133. I need to sync a change across multiple repos.

Is there any update on the status of this?

**Comment by clarketm** [comment]
The newest local PJ testing tool is [`pj-on-kind.sh`](https://github.com/kubernetes/test-infra/blob/4224dd98f2a84dec743a5b8940784f16a414beea/prow/build_test_update.md#using-pj-on-kindsh). While not without its flaws, it can replicate the CI environment quite well. Furthermore, https://github.com/kubernetes/test-infra/issues/13370 is progressing.

[prow/pj-on-kind.sh](https://github.com/istio/test-infra/blob/818552c8ffe6ee9cd1dfdfdb9ec8bb0978a7d8b3/prow/pj-on-kind.sh)

**Comment by howardjohn** [comment]
That is useful but doesn't really fully solve the problem. We have 30 test suites, so its not feasible to run them all locally

**Comment by howardjohn** [comment]
This led to an 1hr+ test breakage because we needed to atomically commit https://github.com/istio/istio/pull/19133 and it had to be tested+retested before it could merge, during which all other tests failed

**Comment by howardjohn** [comment]
I had 3 developers message me about issues with their PRs merging because we couldn't atomically merge https://github.com/istio/istio/pull/19318.

**Comment by howardjohn** [comment]
Another codependant PR issue, we merged test-infra which blocked the repo until https://github.com/istio/operator/pull/698 was merged, but that PR failed other tests, blocking the whole repo

**Comment by howardjohn** [comment]
This is also blocking effective automation of common file updates. For example, one common files change that fails because it needs the same change in test-infra: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_cni/227/lint_cni/83/build-log.txt @clarketm 

It will work sometimes, but if the common files change ever changes the output of `make gen` it will not

**Comment by clarketm** [comment]
> Ideally when the jobs are changed, the new jobs would run in the PR. The only way I can think of achieving this is kubernetes/test-infra#13370, so this issue may just be essentially tracking that.

[**inrepoconfig**](https://github.com/istio/test-infra/issues/2230) has been configured (and stable) for some time now. It is currently being used for a single job (i.e. [checkconfig](https://github.com/istio/test-infra/blob/master/.prow.yaml) - istio/test-infra@master). 

One major downside I see with the transition to using inrepoconfig is job maintenance as the jobs will be scattered over 14+ repos times 2+ active branches. Also, job generation will need to either be triggered in the repo (recommended) or sent via PR to the appropriate `repo@branch` destination. I am working on a prowjob CLI tool that can be invoked to do the former (it is a superset of the existing generate.go logic). There may be other downsides as well related to ease of debugging,  bad configuration detection, job naming conflicts, performance/latency, and compatibility with `istio-private`.  

With that being said, I still think this is the direction we want to go. The benefit greatly outweighs the cost. These downsides can be mitigated if we proceed with caution and rollout gradually. I would appreciate feedback from @istio/wg-test-and-release-maintainers and/or job owners before proceeding with a formal design/plan. But informally, the rough plan would be to migrate smaller repos (e.g. community) and single-branch repos (e.g. bots) first, assess for a period, then proceed accordingly.

**Comment by howardjohn** [comment]
I share basically the same thoughts. It would be great to have the jobs in
repo so that we don't have breakages (any change to generated output
results in a couple hours of "downtime") but it does add some complexity,
so we will need to figure out how we can manage that

**Comment by howardjohn** [comment]
I don't think this has been a major problem these days, and the k8s side is resolve (in repo config)
