### ISSUE TITLE
question: simplify rerun_command/trigger

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1762]
Prow has two fields:

```
   trigger: "(?m)qux test this( please)?" # Regexp, see discussion.
   rerun_command: "qux test this please"  # String, see discussion.
```

Say we have a job `unit-tests_istio_release-1.3`

Right now a user can `/test all`, `/retest`, `/test unit-tests_istio_release-1.3` and they will all trigger it.

A better UX would just be to type `/test unit-tests`

if we set `trigger: /test unit-tests` will this give us expected outcome? 

Specifically, will it be smart enough to not trigger the `unit-tests_istio_release-1.2` (different release) or `unit-tests_OTHERREPO_release-1.3` tests? And will `retest`/`test all` still work or do we need some crazy regex for those?

**Comment by clarketm** [comment]
@howardjohn - link to or create this issue in [kubernetes/test-infra](https://github.com/kubernetes/test-infra) for this. You will reach a broader audience and get more feedback.

**Comment by howardjohn** [comment]
answered in https://github.com/kubernetes/test-infra/issues/14265
