### ISSUE TITLE
Setup Prow job rerun

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#1768]
![image](https://user-images.githubusercontent.com/9957358/64368712-b302dd00-cfcf-11e9-8c66-fc638f775e32.png)

It would be great to expose this feature to existing prow users. The infrastructure is in place - it just needs to be configured.

Tasks:
- [x] An `Istio` owner to create a [Github Oauth App](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/github_oauth_setup.md#set-up-secrets) (step 1 and 2)
- [x]  Add [rerun_auth_config](https://github.com/kubernetes/test-infra/blob/de955ac78f9928febbcef1631c6f298d07ba920d/prow/config.yaml#L47-L52) to Prow `deck` config, #1807.
- [x] Update the `deck` Kubernetes deployment and secrets (`github-oauth-config` and `cookie`), #1807.

**Comment by clarketm** [comment]
@fejta / @howardjohn - can one of you help me with `task 1` (Github Oauth App) above; I do not have the access.

**Comment by howardjohn** [comment]
I can't either, @geeknoid is the right person for this

**Comment by clarketm** [comment]
@geeknoid
Not urgent, but can you assist with `task 1` (Github Oauth App)? (Assuming this is a feature `Istio` wants on FE).

**Comment by fejta** [comment]
Here's how we set this up for k8s: https://github.com/kubernetes/test-infra/blob/de955ac78f9928febbcef1631c6f298d07ba920d/prow/config.yaml#L47-L52
