### ISSUE TITLE
CODEOWNERs randomly not applying

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1776]
I have seen this on this repo and istio/api. At the time of opening, in both these repos codeowners is not applied. Suddenly github stops enforcing codeowners, not sure if it is a github issue or branchprotector or our config.

**Comment by geeknoid** [comment]
As shown in the attached picture, the GitHub UI indicates that code owner review is required, yet PRs don't behave that way. I tried flipping the option off and then on again in the UI and PRs started behaving as expected for a while, and then the behavior reverted. It seems reasonable to think that somehow branch protector is triggering a confused state in GitHub where the UI says code owner approval is required, but the reality of what happens is different.

This might be a bug better handled by GitHub support.

<img width="629" alt="Screen Shot 2019-09-06 at 20 51 46" src="https://user-images.githubusercontent.com/22780957/64469508-33b4fc80-d0e8-11e9-806c-b5a9acc62396.png">

**Comment by howardjohn** [comment]
We figured it out. Invalid owners files cause this -- typos and/or people not in the org/without write access
