### ISSUE TITLE
`/test ...` commands not working

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1833]
Example: https://github.com/istio/istio/pull/17303

Likely broken by https://github.com/istio/test-infra/pull/1817

Typing the `rerun command` is not working, which indicates it may be a prow issue rather than a user error?

**Comment by clarketm** [comment]
Let me see if I can debug this and uncover what the issue in Prow was with the rerun command given.

**Comment by clarketm** [comment]
Have those specific rerun commands (e.g. `/test unit-tests` ever succeeded since the change was made or is the error localized to the referenced PR?

**Comment by howardjohn** [comment]
`/test unit-tests_istio` or whatever worked at one point. I do not know if the shorter `/test unit-tests` ever worked or not.

The reason I suspect its not just a misconfig is that the "rerun command" is required to match the "trigger" regex, so I would expect it to have been rejected if so?

**Comment by fejta** [comment]
Please drop the rerun command. The job name, github context and rerun command should all match.

AKA `job foo` == `context foo` == `/test foo`. 

While we do offer this footgun, nothing should use it.
