### ISSUE TITLE
Migrate ProwJob GitHub reporting from Plank to Crier. 

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#1976]
Migrate ProwJob GitHub reporting from Plank to Crier. 

https://github.com/kubernetes/test-infra/blob/f0f14f5bcd398eab90ec5df74c531237ef802f9c/prow/cmd/crier/README.md

**Comment by chases2** [comment]
Plank is emitting hourly "failure to sync" errors. I think it might be related to this issue.

```
{
  component: "plank"   
  error: "errors syncing: [], errors reporting: [error setting status: status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}]"   
  file: "prow/cmd/plank/main.go:144"   
  func: "main.main.func2"   
  level: "error"   
  msg: "Error syncing."   
 }
```

**Comment by clarketm** [comment]
> Plank is emitting hourly "failure to sync" errors. I think it might be related to this issue.
> 
> ```
> {
>   component: "plank"   
>   error: "errors syncing: [], errors reporting: [error setting status: status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}]"   
>   file: "prow/cmd/plank/main.go:144"   
>   func: "main.main.func2"   
>   level: "error"   
>   msg: "Error syncing."   
>  }
> ```

I do not see this "hourly" error for `plank` in the Istio Prow logs? If `plank` was not syncing, then jobs would not be running: https://prow.istio.io/. Are you sure this is from the Istio Prow instance?

**Comment by fejta** [comment]
Just kidding, wrong prow

**Comment by fejta** [comment]
/reopen

Still outstanding
https://github.com/istio/test-infra/blob/49ea5c6f1ab348b7469a5f0c4b0d8be8eb56946f/prow/cluster/crier_deployment.yaml#L21-L26

**Comment by chases2** [comment]
I didn't see this log during today's update. Is this due to a lack of traffic, or has the problem been resolved?

**Comment by clarketm** [comment]
Yes, this still needs to be migrated, but again I do not think the errors mentioned above are related. I will coordinate with oncall and get this migrated this week.

**Comment by fejta** [comment]
Pending
