### ISSUE TITLE
bazel cannot create symlinks

### ISSUE THREAD

**Issue by kyessenov** [istio/test-infra#1985]
```
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-bin -> /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/execroot/io_istio_proxy/bazel-out/k8-fastbuild/bin:  /home/prow/go/src/istio.io/proxy/bazel-bin (Permission denied)
```

This appears due to mis-aligned permission model - prowbazel runs as user bootstrap but `~/go` is owned by root.

**Comment by clarketm** [comment]
Slack convo: https://istio.slack.com/archives/C6FCV6WN4/p1571867121100600

related: istio/istio#18195

**Comment by clarketm** [comment]
I surmise that changing the [`prowbazel`](https://github.com/istio/test-infra/blob/5bb1e4bfb1f5bf83c38e5eeb1caec399895ca3c3/docker/prowbazel/Dockerfile#L30) image user to `root` will resolve. I need to ensure this has no adverse side-effects before making the change.
