### ISSUE TITLE
Setup e2e suite to test k8s {1.5, 1.6} * {auth, noauth}

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#201]
Based on https://github.com/istio/istio/issues/186
We want to create another cluster for E2E testing and setup different runs/

**Comment by kyessenov** [comment]
RBAC vs non-RBAC, too

**Comment by sebastienvas** [comment]
is nt it included in 1.5 vs 1.6 ?

**Comment by kyessenov** [comment]
RBAC is becoming default in 1.6 but is not backwards compatible with 1.5 (missing fields in YAMLs)

**Comment by sebastienvas** [comment]
Duplicate of https://github.com/istio/istio/issues/478. Please check with Andra what are the the configuration that we want to check.

**Comment by yutongz** [comment]
Do we still need to concern about k8s 1.5/1.6
