### ISSUE TITLE
Use RBE for istio/proxy Bazel builds and tests.

### ISSUE THREAD

**Issue by PiotrSikora** [istio/test-infra#2013]
Existing istio/proxy jobs take ~30 mins for presubmit jobs, and ~2 hours for presubmit-release and postsubmit jobs (both are performing the same build, but postsubmit job publishes artifacts).

Since Prow itself doesn't provide cache, we should consider using RBE for Bazel builds and tests.

Does Prow / EngProd already have shared RBE that we could leverage?

cc @fejta

**Comment by PiotrSikora** [comment]
FWIW, [istio/proxy](https://github.com/istio/proxy) already supports RBE, so the only missing pieces are:
- provisioning RBE buildfarm,
- loading credentials in presubmit jobs (either using the same service account as in postsubmit job, which has more permissions that we need, or creating a new credentials for RBE that we load in Bazel),
- adding `BAZEL_BUILD_ARGS="--config=remote --config=rbe-toolchain-clang-libc++"` (and RBE config) to [`prow/proxy-common.inc`](https://github.com/istio/proxy/blob/master/prow/proxy-common.inc).

**Comment by fejta** [comment]
/assign

I believe I already set one up for istio. Will investigate more next week.

**Comment by PiotrSikora** [comment]
@fejta any updates?

**Comment by fejta** [comment]
The cluster exists:

```
$ gcloud alpha remote-build-execution instances list --project=istio-testing
---
location: us-central1
name: projects/istio-testing/instances/default_instance
state: RUNNING
```


Run:
https://github.com/kubernetes/test-infra/blob/master/rbe/configure.sh istio-testing

Then `bazel build --config=remote-istio-testing //...` in whatever repo should work

Although this will need something like the following in WORKSPACE:
https://github.com/kubernetes/repo-infra/blob/e7bd7a7c8b3f900d5344bf5909c60f890f9719aa/repos.bzl#L1251

which you can either do manually or else do it by importing repo-infra, like the following repos do:
https://github.com/kubernetes/test-infra/blob/eab838ec13a6c3f1269e2764190920b0e7c99a7b/WORKSPACE#L8-L17

https://github.com/GoogleCloudPlatform/testgrid/blob/master/WORKSPACE#L4-L25

AKA see https://cloud.google.com/remote-build-execution/docs/set-up/remote-environment#add_the_provided_toolchain

At that point we'll then need to make prowjobs inject credentials to a service account that can talk to this RBE instance by doing something like:

https://github.com/kubernetes/test-infra/blob/eab838ec13a6c3f1269e2764190920b0e7c99a7b/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L52-L61

Looks like the jobs already inject a service account:

https://github.com/istio/test-infra/blob/71749c93d3481b5af44fa25a6a9211ee5f07371e/prow/cluster/jobs/istio/proxy/istio.proxy.master.yaml#L22-L23

So we should make sure this identity has the right scopes:

https://github.com/istio/test-infra/blob/71749c93d3481b5af44fa25a6a9211ee5f07371e/prow/config.yaml#L315-L327

**Comment by fejta** [comment]
That account -- istio-prow-test-job@istio-testing.iam.gserviceaccount.com -- now has the right scopes so you just need to update the job to use it

**Comment by PiotrSikora** [comment]
Hey @fejta, could you change the worker pool for RBE to use `n2-standard-2` instances, instead of `n1-standard-2`? `n2` are quite a bit faster, and we're seeing some timeouts with `n1`. Thanks!

cc @lizan

**Comment by fejta** [comment]
```
$ gcloud alpha remote-build-execution worker-pools update prow-pool --instance=default_instance --project=istio-testing  --machine-type=n2-standard-2
Request issued for: [prow-pool]
Waiting for operation [projects/istio-testing/operations/EAMacHByb2plY3RzL2lzdGlvLXRlc3RpbmcvaW5zdGFuY2VzL2RlZmF1bHRfaW5zdGFuY2Uvd29ya2VycG9vbHMvcHJvdy1wb29sIDQ2YThlNjZmLTJlMTctNGFkOS1iOWMzLWI1ZWY4MWI4NTE4OCAyMDAiHFdvcmtlclBvb2xzLlVwZGF0ZVdvcmtl
clBvb2w=] to complete...⠧   
```
