### ISSUE TITLE
Credential mount failing for post-test-infra-upload-testgrid-config

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2036]
The job [`post-test-infra-upload-testgrid-config`](https://github.com/istio/test-infra/blob/4f348d436ac859b9304d052878b4813f61536bf3/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L96) is [failing](https://prow.istio.io/view/gcs/istio-prow/logs/post-test-infra-upload-testgrid-config/1190349260122492934) due to a failed mount. As the error states, the `[github_token]` argument can't be found.

The job contains the secret as a volume mount, and the secret is present on the service cluster in the `test-pods` namespace.

**Comment by chases2** [comment]
New [error](https://prow.istio.io/view/gcs/istio-prow/logs/post-test-infra-upload-testgrid-config/1190349260122492943):

```
time="2019-11-06T03:06:37Z" level=info msg="CreatePullRequest(kubernetes, test-infra, Update TestGrid for istio)" client=github
time="2019-11-06T03:06:37Z" level=fatal msg="Failed to ensure PR exists." error="create error: status code 422 not one of [201], body: {\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"PullRequest\",\"field\":\"head\",\"code\":\"invalid\"}],\"documentation_url\":\"https://developer.github.com/v3/pulls/#create-a-pull-request\"}"
```

I'm inspecting the token and the call to `pr-creator` to see what the issue might be.

/assign

**Comment by chases2** [comment]
The token only has read access to public repositories; a different token is needed in the service cluster's `test-pods` namespace.

/assign @clarketm

**Comment by clarketm** [comment]
@chases2 were you able to get this working with the existing token? It has correct scopes.

**Comment by chases2** [comment]
Yes, the job has been regularly succeeding with the current token scopes.
