### ISSUE TITLE
Automate istio/api cross-repo file generation and propagation

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2103]
If a change is done in a branch of `istio/api`, we should trigger an update in the *same* branch of `istio/client-go`, followed by an update in the *same* branch of `istio/istio`.

**e.g.**
1. A change occurs (e.g. PR merged in `istio/api`)
2. In response to this *initial* change in `istio/api`, in `istio/client-go` we will run:
```sh
# update `istio/api` dependency
go get "istio.io/api@<branch>"

# regenerate files
make gen

# Push change to a PR
git push ...
```

3. In response to the changes in `istio/api` `istio/client-go`, in `istio/istio` we will run:
```sh
# update `istio/api` dependency
go get "istio.io/api@<branch>"

# update `istio/client-go` dependency
go get "istio.io/client-go@<branch>"

# regenerate files
make gen

# Push change to a PR
git push ...
```

---

The trigger for 1 -> 2 should be a standard `postsubmit` job run after *any* change to `istio/api` that creates a PR to `istio/client-go` with changes. The trigger from 2 -> 3 also will be `postsubmit` job run after *any* change that will create a PR to `istio/istio` with changes. 

If we want to tweak the "after *any*" part we can get more sophisticated with trigger.

**Comment by clarketm** [comment]
cc @geeknoid

**Comment by howardjohn** [comment]
I don't think istio/istio depends on client-go? or is that planning on changing?

Note we also have a new bin/update_deps.sh script in istio/istio that also updated proxy, cni, etc

**Comment by clarketm** [comment]
> I don't think istio/istio depends on client-go? or is that planning on changing?

I transcribed this from email from @geeknoid, so I must defer to him  Now that you mention it, I don’t see that association in the dep list.

**Comment by clarketm** [comment]
> Note we also have a new bin/update_deps.sh script in istio/istio that also updated proxy, cni, etc

Thanks. The commands above are a general flow, if there are utility scripts available we should prefer those. And if there are additional deps to update we should bundle in this same pipeline.

**Comment by geeknoid** [comment]
We plan to start using istio/client-go from istio/istio soon.

**Comment by geeknoid** [comment]
@nrjpoddar FYI

**Comment by geeknoid** [comment]
Note that this automatic upgrade procedure is likely to encounter failures due to the occasional need for coordinated multi-repo updates. For example, if I change something in istio/api, I might need a corresponding change in istio/istio.

**Comment by clarketm** [comment]
> Note that this automatic upgrade procedure is likely to encounter failures due to the occasional need for coordinated multi-repo updates. For example, if I change something in istio/api, I might need a corresponding change in istio/istio.

@geeknoid - are the "coordinated multi-repo updates" in addition to the *dependency* and *gen* updates mentioned in the description above? Is this because the required code updates are bidirectional? (i.e. a change in `istio/api` requires a change in `istio/istio` which in turn requires a change back in `istio/api`). 

If we can get a *strict* sequence of events/changes here (including any test updates) we can likely mitigate this. If someone can help me flesh out the process sequence, then I can figure out a way to make atomic changes so we are never in a broken, outdated state.

**Comment by howardjohn** [comment]
We don't have bidirectional issues. The problem is if the import has breaking changes we cannot just `go get new-version`, we also need to make manual changes to the code base. I think there is nothing automation can do about this

**Comment by clarketm** [comment]
> We don't have bidirectional issues. The problem is if the import has breaking changes we cannot just go get new-version, we also need to make manual changes to the code base. I think there is nothing automation can do about this

I am not sure what the need is if this strictly *cannot* be automated and *requires* steps that can only be done manually 😕. Please reopen if this is not the case or if there is any automation we can leverage.

**Comment by howardjohn** [comment]
I cannot reopen, can you please?

We can update automatically 90% of the time. In 10% of cases (randomly made up stat) we will need human intervention

**Comment by clarketm** [comment]
> We can update automatically 90% of the time. In 10% of cases (randomly made up stat) we will need human intervention

Sorry I misunderstood. For that ~10%, we can at least have early detection of failure with presubmits and a starting point (i.e. branch and PR) for developers to work from. ... so since failure is that *uncommon* we should proceed which this automation as it will be helpful in most cases.

**Comment by nrjpoddar** [comment]
> We can update automatically 90% of the time. In 10% of cases (randomly made up stat) we will need human intervention

I think that's fine, we should at least attempt to recognize changes in our dependency repositories and submit a PR which may or may not build. Humans can take over after that for the final 10%.

**Comment by clarketm** [comment]
cc @Biwwie

**Comment by ericvn** [comment]
Pointer to [The consistent rollout of common-files](https://docs.google.com/document/d/1d4tB3LCeoRcW_TEj_4TMpJSaeSF8H0iSUa5Ln2k1l4I/edit#)

**Comment by clarketm** [comment]
> Pointer to [The consistent rollout of common-files](https://docs.google.com/document/d/1d4tB3LCeoRcW_TEj_4TMpJSaeSF8H0iSUa5Ln2k1l4I/edit#)

This is the correct reference issue for `common-files`: https://github.com/istio/test-infra/issues/1627
