### ISSUE TITLE
Fetch and visualize metrics for developing health

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#211]
Currently, we have several metrics tracking issues, pull-request-related info on velodrome.istio.io In order to monitor developing process and support external contributors better, extra metrics are required like build duration, recent build failure rate, code coverage changing. Release support is also something we are interested.

**Comment by yutongz** [comment]
Done fetch from Jenkins: [velodrome](https://velodrome.istio.io/dashboard/db/coverage?orgId=1)
Will work on prow metrics fetching on Sept.

**Comment by yutongz** [comment]
/unassign @yutongz
I am not working on this right now.

**Comment by fejta** [comment]
Should probably use 
https://devstats.cncf.io/
https://github.com/cncf/devstats

for this sort of thing

**Comment by clarketm** [comment]
@fejta - It looks like Istio stats *do* exist in devstats on the **test** server: https://istio.teststats.cncf.io

**Comment by fejta** [comment]
Awesome! I wonder if anyone is aware of this yet? We should change that!

**Comment by clarketm** [comment]
The best way to achieve this would be to [promote](https://github.com/cncf/devstats/blob/79dada9e6319ce402a4794242af62add4a0bc326/ADDING_NEW_PROJECT.md#to-add-new-project-on-the-production-when-already-added-on-the-test-you-should-use-automatic-deploy-script) this dashboard to *production*. @geeknoid is aware of this (e.g. istio/istio#13891 / cncf/devstats#181); there are additional, unsatisfied feature request before this is *production-ready*.

---

I am closing this as a duplicate of: istio/istio#13891

**Comment by howardjohn** [comment]
I thought to get it to production we had to join the cncf. If that is not
the case it would be great if we did the work to get onto production.

I think there are a decent number of people who look at the dashboards
