### ISSUE TITLE
Hook: trusted_org is deprecated and may be out by 2020

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2114]
```
{
  component: "hook"   
  file: "prow/plugins/config.go:653"   
  func: "k8s.io/test-infra/prow/plugins.warnDeprecated"   
  level: "warning"   
  msg: "trusted_org functionality is deprecated. Please ensure your configuration is updated before the end of December 2019."   
 }
```

**Comment by clarketm** [comment]
ref: https://github.com/istio/test-infra/pull/2028

**Comment by fejta** [comment]
/assign @fejta @howardjohn 

John any progress on adding people to istio-releases and istio-ecosystem?

How about if we start using peribolos to reduce the cost of this maintenance?

**Comment by fejta** [comment]
How do I triage this issue as normal?

**Comment by howardjohn** [comment]
I updated https://github.com/istio/istio/wiki/Issue-and-Pull-Request-Lifecycle-Manager to be more clear. I think for triage this means assigning a priority in zenhub (not a fan but its what we use..).

As far as the org I do not have access to it. We should just switch to peribolos

**Comment by fejta** [comment]
Is istio using peribolos these days?

**Comment by howardjohn** [comment]
Yes, we are now on peribolos

**Comment by fejta** [comment]
Sweet! Can we remove the trusted_org bit now then?

**Comment by howardjohn** [comment]
We will need to copy everyone over to these orgs, but then we should be good to remove it?

**Comment by fejta** [comment]
sgtm

**Comment by fejta** [comment]
I can send a PR to do that if you point me to where the config is stored

**Comment by howardjohn** [comment]
https://github.com/istio/community/blob/master/org/istio.yaml. Thanks!
