### ISSUE TITLE
chases2: Request for permission to rerun Prow Jobs

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2117]
The rerun button in Prow prompts me to login via GitHub, but then specifies that I don't have permission to rerun a job.

Specifically, I needed to rerun `ci-prow-autobump` as part of the oncall update process. I suspect that my GitHub username isn't in the right group.

**Comment by howardjohn** [comment]
You can add https://github.com/istio/test-infra/blob/master/prow/config.yaml#L48. Maybe we should make a group for istio oncall folks, or reuse one from k8s if it exists

**Comment by clarketm** [comment]
> Maybe we should make a group for istio oncall folks, or reuse one from k8s if it exists

I would prefer an Istio specific group so we can decouple Istio oncall from K8s oncall (in case they ever diverge). In the meantime @chases2, just send out a PR and add your username to [config.yaml](https://github.com/istio/test-infra/blob/22f8e7d6e7c4603815446bdd9aeaeaeec8872551/prow/config.yaml#L47-L55) as @howardjohn pointed out.

**Comment by clarketm** [comment]
fixed by https://github.com/istio/test-infra/pull/2250
