### ISSUE TITLE
Tide merge strategy labels

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2133]
Consider adding GitHub [labels](https://github.com/kubernetes/test-infra/blob/4ab1254b17178ffd0d0757f1d034acb21f4ccb50/prow/config/tide.go#L111-L124) for enabling the various different Tide [merge strategies](https://github.com/kubernetes/test-infra/blob/4ab1254b17178ffd0d0757f1d034acb21f4ccb50/prow/github/types.go#L87-L91) on different PRs.

**Comment by clarketm** [comment]
@geeknoid - can you shed some light on how Istio currently manages and synchronizes labels across the various GitHub orgs and repos?

**Comment by geeknoid** [comment]
We use the policybot's label manager: https://github.com/istio/bots/blob/master/policybot/cmd/labelmgr.go

This is run in a cron job. The set of supported labels is defined in https://github.com/istio/bots/blob/master/policybot/policybot.yaml

There is currently no way to delete labels automatically, only add/edit 'em.

**Comment by geeknoid** [comment]
But in general, as a project, we explicitly have not wanted to support the other merge strategies. It can lead to out of control history since some engineers use "micro commits" and end up with dozens of commits per PR.

**Comment by clarketm** [comment]
> But in general, as a project, we explicitly have not wanted to support the other merge strategies. It can lead to out of control history since some engineers use "micro commits" and end up with dozens of commits per PR.

Makes sense as a general workflow. The one exception where I thought this may be helpful is for the `istio-private` org; we may want either a rebase or fast-forward merge strategy to be imposed on specific PRs crafted to sync with upstream. Although, I am not convinced that this is any simpler than rebasing and force pushing.

**Comment by clarketm** [comment]
> There is currently no way to delete labels automatically, only add/edit 'em.

Is not having delete by design or missing functionality? If the latter, then this could be generally useful (e.g. removing labels for old, unsupported releases: `cherrypick/release-1.0`) and a good opportunity for a community contribution.
