### ISSUE TITLE
Need a way to test postsubmit jobs in presusbmit

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2171]
We have a few tests that run in postsubmit only due to length/quantity of the tests. Because they aren't blocking merges, they occasionally get broken. When fixing these tests, its mostly trial and error, since we can't actually tell if it fixed the issue until it is merged unless we run it locally (which may take hour+). 

It would be nice if we could manually trigger a postsubmit in a PR so we can verify it will fix any issues

**Comment by clarketm** [comment]
This is definitely a universal Prow limitation/problem and I too would love to come up with an elegant solution. The best idea I have (specifically for `postsubmits`) is what I mentioned in: https://github.com/kubernetes/test-infra/issues/14655.  

Ideally, Prow would expose an API (and/or a better front-end) where jobs can be queried, created, or run on-demand with minimal effort. 

Also, while alternatives like `mkpod` and `mkpj` are useful for general debugging and job creation, they are not the most user friendly and require direct cluster access to apply.

**Comment by clarketm** [comment]
With [inrepoconfig](https://github.com/istio/test-infra/issues/1734#issuecomment-604281159), we could define these as _optional_ (non-blocking) presubmits. Would that solve the problem? Also, what are the specific jobs in question?

**Comment by howardjohn** [comment]
I think this is less of a concern now since we are trying to make all jobs
presubmit if possible. In repo config could be used as well though if it's
not too much burden/impact on setting it up and on devs - I haven't looked
too closely at it

**Comment by howardjohn** [comment]
This is now done by option jobs
