### ISSUE TITLE
authentikos appears stuck

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2195]
```console
authentikos-6558cb9ff5-tkknc        1/1     Running             0          11d
authentikos-849c4467d5-5m8sf        0/1     ContainerCreating   0          20h
```

**Comment by clarketm** [comment]
This is stuck in the `istio-testing` cluster, right? Authentikos should only be configured to run in the *private* cluster; this explains why the secret needed for the volume mount is not available and it cannot create the container.

**Comment by fejta** [comment]
Yes, any idea why its running then? Maybe something forgotten from testing?

**Comment by clarketm** [comment]
> Yes, any idea why its running then? Maybe something forgotten from testing?

The make `deploy-private` recipe is correct. Yes, I think this was simply forgotten from early prototype testing.

I will delete the `authentikos` deployment (clusterrole, etc.) from `istio-testing`.

**Comment by clarketm** [comment]
I removed the errant `authentikos` deployment, clusterrole, clusterrolebinding, and serviceaccount from `istio-testing` cluster.

**Comment by fejta** [comment]
`authentikos-849c4467d5-knrff        0/1     ContainerCreating   0          20h`

**Comment by clarketm** [comment]
🤔 . Looks like the `make` command does not rerun the `get-cluster-credentials` pre-recipe before each target in the [postsubmit](https://github.com/istio/test-infra/blob/7aee3a633f67ca34e243f3058c61699f6e93429e/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L17-L24), so effectively everything gets deployed to service cluster.
