### ISSUE TITLE
Enable and configure GKE auto scaling

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2196]
The GKE [auto scaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md) is configurable enough so that we can scale up during peak demand and scale down during low demand (while preventing pods from being erroneously aborted/terminated with grace period tuning). This will significantly reduce operational costs in the long run.

This will be evaluated at a smaller scale on a single node pool for only a subset on the Istio jobs (i.e. non-critical jobs). It can be applied (for the initial test) via Kubernetes node selector.

**Comment by howardjohn** [comment]
Can we fine tune on GKE? I don't see where to do it in the UI or in https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler

**Comment by clarketm** [comment]
> Can we fine tune on GKE? I don't see where to do it in the UI or in 

I cannot find any documentation or options for these advanced configuration options either, so it is likely that the CA cannot be tuned (beyond `min` and `max` nodes) in GKE. 

I will need to investigate further.

**Comment by clarketm** [comment]
Autoscaling was enabled on test node pool.
