### ISSUE TITLE
Velodrome TLS cert not auto-renewing

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2207]
The **velodrome** (https://velodrome.istio.io) TLS cert is **not** auto-renewing and expires **12/19/19**.

![image](https://user-images.githubusercontent.com/9957358/70607094-adaac500-1bb2-11ea-928b-27ebdb49efd8.png)

**Comment by clarketm** [comment]
`gcsweb.istio.io` is also not renewing.

**Comment by howardjohn** [comment]
gcsweb expiring is pretty bad, last time this happened a bunch of people yelled at us because they are apparently indirectly depending on gcsweb. We added a job to monitor that its up but I guess didn't get auto rotation working

**Comment by clarketm** [comment]
> gcsweb expiring is pretty bad, last time this happened a bunch of people yelled at us because they are apparently indirectly depending on gcsweb. We added a job to monitor that its up but I guess didn't get auto rotation working

I agree this is bad. The version of `certmanager` currently in use is obsolete (and likely the cause of the failure to auto renew). I am working on resolving this now.
