### ISSUE TITLE
Investigate the Prow and istio/bots welcome plugins as a way greet new contributors to Istio org.

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2213]
Prow has a [`welcome`](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/welcome) plugin and `istio/bots` has a [`welcomer`](https://github.com/istio/bots/tree/master/policybot/handlers/githubwebhook/welcomer) plugin that can be utilized to greet *new* contributors to Istio. 

We should compare the features between both the Istio bot and Prow welcome plugins before a decision is made regarding org adoption.

#### Examples:
**Prow**:  https://github.com/istio/test-infra/pull/2219
**Istio Bots**: https://github.com/istio/bots/pull/116

cc @geeknoid @istio/wg-test-and-release-maintainers

**Comment by clarketm** [comment]
@geeknoid @istio/wg-test-and-release-maintainers  

I would appreciate any feedback regarding *"content"* of the welcome message and which approach we want to take as an org. There is more-or-less feature parity between the two alternatives. Prow has a few [template substitutions](https://github.com/kubernetes/test-infra/blob/988de4206a68fc2514f37e530169dcda008e69d8/prow/plugins/welcome/welcome.go#L41-L46) available in the message (but that should be trivial to add to Istio bot if desired). 

#### Examples:
**Prow**:  https://github.com/istio/test-infra/pull/2219
**Istio Bots**: https://github.com/istio/bots/pull/116

Personally, I like to  Istio bot `welcomer` @geeknoid engineered b/c it is leveraging the bot infrastructure he already built, it is decoupled from Prow (which is good or bad), allows custom messaging by repo, has a notion of [resending](https://github.com/istio/bots/blob/f89495dac487fedc7e4827a127d52f9e67600c73/policybot/handlers/githubwebhook/welcomer/record.go#L29-L31) of the message for *infrequent* contributors, and will promote a consistent brand image across the org (as it is currently utilized by `istio.io`). That being said, the Prow version has many of these same benefits with the additional value added that it is already actively maintained.

**Comment by geeknoid** [comment]
I decided to implement the Istio welcomer because I wanted to resending feature. As people 'drift away' from the project and rejoin, it's useful to remind 'em of the processes. The bot is pretty simple and has been working well as it is. It's nice that it's per-repo since it lets you give different recommendations to users.

**Comment by clarketm** [comment]
Unless there are objections, I say we continue forward with the `istio/bots` [`welcomer`](https://github.com/istio/bots/tree/master/policybot/handlers/githubwebhook/welcomer) plugin. The switching cost is low if we ever want to leverage Prow for this in the future.

**Istio Bots:** istio/bots#116

**Comment by clarketm** [comment]
[Merged](https://github.com/istio/bots/pull/116) and [deployed](https://storage.googleapis.com/istio-prow/logs/deploy-policybot_bots_postsubmit/13/build-log.txt), so welcomer bot will not comment for **istio/test-infra**. Let's evaluate for a short duration then rollout to other repos.

**Comment by clarketm** [comment]
The welcomer bot has **not** triggered a welcome message in **istio/istio.io** since mid-Dec 2019:

https://github.com/istio/istio.io/pulls?utf8=%E2%9C%93&q=is%3Apr+in%3Acomments+%22Welcome%21+This+is+either+your+first+contribution+to+the+Istio%22+sort%3Aupdated-desc+commenter%3Aistio-testing+

and **never** for **istio/test-infra**:

https://github.com/istio/test-infra/pulls?utf8=%E2%9C%93&q=is%3Apr+in%3Acomments+%22Welcome%21+This+is+either+your+first+contribution+to+the+Istio%22+sort%3Aupdated-desc+commenter%3Aistio-testing+
