### ISSUE TITLE
Evaluate inrepoconfig

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2230]
Evaluate using [inrepoconfig](https://github.com/kubernetes/test-infra/blob/2b88bfc4b06c4c0f450e1f844c26656164430d32/prow/inrepoconfig.md) to increase developer productivity especially for cross-repo changes (e.g. propagation of common files: #1627).

This issue will also track implementation.

cc @istio/wg-test-and-release-maintainers

**Comment by howardjohn** [comment]
Possibly interesting but not currently planned
