### ISSUE TITLE
Migrate to workload-identity

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2282]
Jobs running on GKE should use https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity to authenticate with GCP rather than by loading a json file from a secret

**Comment by praveenbingo** [comment]
@howardjohn Does istio work with gke workload identity. I am running into issues trying to setup istio with gke workload identity (it is unable to use the credentials from the identity). 

I googled around a ton, but unable to find any documentation which clarifies the support either positively or negatively :)

**Comment by howardjohn** [comment]
This is mostly done, through a variety of PRs  over the years. https://github.com/istio/test-infra/pull/4790 should be the last one
