### ISSUE TITLE
peribolos: sync gives a 404

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2294]
https://prow.istio.io/view/gcs/istio-prow/logs/sync-org_community_postsubmit/4

Not sure what happened, previous runs worked fine. I know github gives 404 for permission denied but I don't think we changed any permissions

**Comment by howardjohn** [comment]
Hm I think they deleted their github account

**Comment by howardjohn** [comment]
removing them from the org fixed things. We can close or bring this up to k/test-infra if we consider it a bug, but its actually pretty reasonable behavior I think

**Comment by clarketm** [comment]
> removing them from the org fixed things. We can close or bring this up to k/test-infra if we consider it a bug, but its actually pretty reasonable behavior I think

@howardjohn Keep open for now, while I investigate. Maybe just adding a flag to `peribolos` (if it does not already exists) that reduces this error from a *fatal* to *warning* level might be warranted, so we can continue processing (similar to what was done with the branch protector) when this happens might be a good idea.

**Comment by clarketm** [comment]
fixed by: https://github.com/kubernetes/test-infra/pull/16018
