### ISSUE TITLE
Consider making automator auto-approved

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2304]
Right now its a bit of a pain to go approve ~10 PRs when automator spits them out. It would be nice if they just auto merged. I am not sure if there are any implications of this, but I think we could do this with a tide query that looks like `author:istio-testing label:automator` or something similar. 

We may also want to wait a few weeks for it to mature before doing this

**Comment by clarketm** [comment]
> We may also want to wait a few weeks for it to mature before doing this

There is some work needed in `tide` (that I am collating) to make this possible, so waiting a few weeks SGTM.

**Comment by clarketm** [comment]
This is feasible now that https://github.com/kubernetes/test-infra/pull/16039 has merged. To make this happen, I need to:
- [x] create a new label (e.g. `auto-merge`) (https://github.com/istio/bots/pull/132)
- [x] apply label somewhere in Automator code (https://github.com/istio/test-infra/pull/2403)
- [x] update `Tide` configuration (https://github.com/istio/test-infra/pull/2404)

**Comment by clarketm** [comment]
success 🍾: https://github.com/istio/api/pull/1271, https://github.com/istio/pkg/pull/110, etc.
