### ISSUE TITLE
Enable Automated Release Note Generation

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#231]
Our current release note generation is manual and therefore nonexistent. We can get assistance from @david-mcmahon and team on how to set this.

**Comment by ldemailly** [comment]
that'd be nice!

**Comment by yutongz** [comment]
Working on it

**Comment by david-mcmahon** [comment]
cc @roycaihw

**Comment by sakshigoel12** [comment]
Monitoring and Educating more.

**Comment by sakshigoel12** [comment]
Closing this. open new one for next milestone
