### ISSUE TITLE
Create a Cluster Pool for daily Qualification

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#234]
Istio is going to be running in its own namespace. Same thing for istio-ca. It would be helpful to have a manager pool of cluster to do the testing such that each test does not need to wait for cluster creation.

let s use this for qualification at first, not for smoke testing.

**Comment by sakshigoel12** [comment]
yutongz@ and andraxylia@ to find next steps for 0.2

**Comment by sakshigoel12** [comment]
Working on design doc

**Comment by sebastienvas** [comment]
this is now in place. We decided to extend k8s Boskos. Here is the design doc  http://goo.gl/vHNfww.

**Comment by sebastienvas** [comment]
We are currently using this on e2e tests in pre and postsubmit
