### ISSUE TITLE
Compare CI solutions

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#236]
The list of comparision should include:
- Kokoro
- Container Cloud Builder
- Drone.io
- Prow

and point out the pain points of our existing Jenkins bases infra.

**Comment by nlandolfi** [comment]
this is done, do we want to post the doc somewhere? otherwise can close this...

**Comment by sebastienvas** [comment]
The doc contains Google Specific code name. You can clean it up and make
sure it is shared on the team drive.
