### ISSUE TITLE
Enable presubmits for istio/envoy

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2385]
cc @PiotrSikora @howardjohn

**Comment by PiotrSikora** [comment]
This should be as easy as calling:
```
bazel build --config=libc++ //source/exe:envoy
bazel test --config=libc++ //test/...
```

**Comment by clarketm** [comment]
> This should be as easy as calling:
> 
> ```
> bazel build --config=libc++ //source/exe:envoy
> bazel test --config=libc++ //test/...
> ```

@PiotrSikora 

Rather than performing a direct `bazel` build and test, can we leverage some of the *existing* test scripts/targets in [do_ci.sh](https://github.com/istio/envoy/blob/master/ci/do_ci.sh) or is that specific to upstream envoy or Azure CI? 

Also, what are the environmental requirements? I see a reference to the `envoyproxy/envoy-build` docker image in the [ci/README.md](https://github.com/istio/envoy/blob/master/ci/README.md#build-image-base-and-compiler-versions).

**Comment by PiotrSikora** [comment]
Hmm, you could use that indeed (or better: [`do_circle_ci.sh`](https://github.com/istio/envoy/blob/master/ci/do_circle_ci.sh) wrapper around it).

**Comment by PiotrSikora** [comment]
Thanks, @clarketm, this is great!

**Comment by clarketm** [comment]
I will add tests for `bazel.tsan` and `bazel.release` as well.

**Comment by PiotrSikora** [comment]
Actually, any chance that you could bump those tests to 16 or more vCPUs? It's incredibly slow with 8 (effectively 6) vCPUs.

**Comment by PiotrSikora** [comment]
Also, ASan didn't finish yet, but I suspect it might run out of disk space before it's done.

**Comment by PiotrSikora** [comment]
Yeah, ASan builds needs a little over 300GB (and growing).

**Comment by clarketm** [comment]
@PiotrSikora 

We have full capability to refine the resources as needed for **istio/envoy** whether that be: 
* adjust the kubernetes resource request; 
* modify bazel `BAZEL_BUILD_EXTRA_OPTIONS `;
* run in a separate node pool;
* or a combination of the aforementioned.

Let me know what is needed for the jobs and I can make the changes.

**Comment by PiotrSikora** [comment]
We definitely need more disk space for `istio/envoy`. I'd go with 512GB SSD disk, but I suspect that ~400GB should also work.

On the CPU front, with 6 vCPUs, all tests are hitting the 2h time limit. Generally, the more the better, so if we can get 32 vCPUs (limited to 30 vCPUs for Bazel) that would be great. This is true for both: `istio/envoy` and `istio/proxy`.

I don't think we need a separate pool.

Thanks!

**Comment by clarketm** [comment]
The other requirements can all be met with current node pool via configuration except the current disk size is only 256GB.

**Comment by clarketm** [comment]
What is all this space used for? Is it from bazel and is output/artifacts to a deterministic location? We can utilize a volume mount ... or just increase disk space.

**Comment by PiotrSikora** [comment]
All this space is used by Envoy tests in `bazel-bin/test/`:
```
$ du -hs bazel-bin/test/
294G    bazel-bin/test/
```
so the location is deterministic (`$HOME/.cache/bazel`), but I'm not sure how this helps with the disk space.

**Comment by clarketm** [comment]
> so the location is deterministic (`$HOME/.cache/bazel`), but I'm not sure how this helps with the disk space.

My thought was as an alternative we could mount in external storage to the job(s) and bazel could write there, then we wouldn't need to increase node VM size. But increasing disk space on node is fine too; will need some time to increase quota and migrate.

**Comment by PiotrSikora** [comment]
Using external storage would persists Bazel cache across builds (which would be a huge win), correct?

**Comment by clarketm** [comment]
> Using external storage would persists Bazel cache across builds (which would be a huge win), correct?

If setup correctly, yes that would be a benefit to this approach. I think k8s does something similar using [greenhouse](https://github.com/kubernetes/test-infra/tree/master/greenhouse) which may be an option.

**Comment by clarketm** [comment]
This is the best we can do atm through config: https://github.com/istio/test-infra/pull/2411. I will issue a quota increase and migrate node pools next week so we can further optimize, then look into cache.

**Comment by PiotrSikora** [comment]
Do you have any visibility into why ASan and TSan jobs are constantly restarted? See:
https://prow.istio.io/job-history/istio-prow/pr-logs/directory/test-asan_envoy_release-1.5

I suspect they are running out of disk space, but the log entry is a bit weird:
```
{"component":"entrypoint","file":"prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2020-02-22T18:40:43Z"}
```

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_envoy/160/test-asan_envoy_release-1.5/52 which is marked as failed I think was interrupted by you force pushing possibly? The others are in some bad state where they are "running" for 13hrs+ though, I assume they got killed in some way and were not able to report the end of the job. ill try to track a running pod to see if we can get any info before it dies

**Comment by PiotrSikora** [comment]
@howardjohn run 52 was indeed interrupted by me force pushing dummy commit to let the job pickup the new config (it looks that retries jobs are using the old config). But as you can see, since then, there are 14 new runs that all get retried at one point or another.

**Comment by howardjohn** [comment]
Yep, all the log info on those is lost though from what I can see. I am tailing the pod from on of them so maybe I'll see how it breaks

**Comment by PiotrSikora** [comment]
If you can run `df -h` in a loop and see it getting close to zero right before restart, then it's running out of disk space, and we need to wait for the pool migration to fix that (see the discussion above).

**Comment by howardjohn** [comment]
![2020-22-02_14-30-54](https://user-images.githubusercontent.com/623453/75100234-f225ea00-557f-11ea-8518-358794004860.png)

I didn't see anything from k8s, but the node shows it gets up to 250gb so seems likely that was the issue

**Comment by PiotrSikora** [comment]
Yeah, those tests are kicked off with 242G of free space, so look that they're running out of disk space indeed. Maybe let's disable ASan & TSan until we sort this out? Otherwise, it's just wasting resources.

**Comment by howardjohn** [comment]
SGTM, ill send a pr

**Comment by howardjohn** [comment]
https://github.com/istio/test-infra/pull/2414

**Comment by PiotrSikora** [comment]
Could you check why Asan is getting constantly retried? Too little resources?
https://prow.istio.io/job-history/istio-prow/pr-logs/directory/test-asan_envoy

**Comment by clarketm** [comment]
> Could you check why Asan is getting constantly retried? Too little resources?
> https://prow.istio.io/job-history/istio-prow/pr-logs/directory/test-asan_envoy

One observation is that only 375.66 GB of allocatable storage is avaialble, so we should probably explicitly add `ephemeral-storage` to the resource request. 

Otherwise, I am tailing the pod logs to uncover more info.

**Comment by howardjohn** [comment]
`kubelet has disk pressure` on one of the nodes running a pod

**Comment by clarketm** [comment]
> `kubelet has disk pressure` on one of the nodes running a pod

I see that now as well.

**Comment by howardjohn** [comment]
One thing as well is we have seen istio/istio tests with issues like `etcd` timeouts, etc (etcd here is Kind, not the prow cluster), possibly related to these changes. I am not sure if its the 32 core machines or interference from envoy jobs. But maybe it makes sense to use different node pools again, and have giant ones for envoy (with autoscaling) and move the istio ones back to 16 core machines?

**Comment by clarketm** [comment]
> Warning  Evicted    3s    kubelet, gke-prow-test-pool-e4d3c275-zhxg  

> The node was low on resource: ephemeral-storage. Container test was using 65458536Ki, which exceeds its request of 0. Container sidecar was using 40Ki, which exceeds its request of 0.

The message just before the pod is evicted. So ultimately the storage is inadequate (hence disk pressure). We should increase storage and add storage requests/limits. 

Either to the existing node pool or a different one.

**Comment by PiotrSikora** [comment]
Sounds like we don't request any storage, only CPU and RAM? This node pool should be sufficient in size, I think.

**Comment by clarketm** [comment]
> Sounds like we don't request any storage, only CPU and RAM? This node pool should be sufficient in size, I think.

Correct, I am adding `ephemeral-storage` requests/limits now and will PR. 

@howardjohn - I have no preference regarding reverting to using a separate node pool again. We can do that if it is preferred and has additional benefits.

**Comment by clarketm** [comment]
> One thing as well is we have seen istio/istio tests with issues like `etcd` timeouts, etc (etcd here is Kind, not the prow cluster), possibly related to these changes. I am not sure if its the 32 core machines or interference from envoy jobs. But maybe it makes sense to use different node pools again, and have giant ones for envoy (with autoscaling) and move the istio ones back to 16 core machines?

If the issues persist after #2427, then we can reinstate separate node pools.

**Comment by clarketm** [comment]
Apparently 512GB disks are not enough ... or 400GB is too large of a request.

> pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 Insufficient ephemeral-storage


@PiotrSikora - 375.66GB is what is allocatable; how much storage space do these jobs actually need? is this enough?

**Comment by clarketm** [comment]
Reinstated a separate `testing: build-pool` node pool for istio/{proxy,envoy}: https://github.com/istio/test-infra/pull/2428 with more than enough resources (also auto-scaled) and will reinstate the 16 cpu node pool for `testing: test-pool` node pool.
