### ISSUE TITLE
Cherrypicker: report issue on failed cherrypick

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2423]
We often see cherrypicks fail and devs don't notice. It would be nice to create an issue for failed cherrypicks, that way they can be easily tracked. Bonus points if it sets the milestone and priority, but those are Istio specific so that may not be feasible

**Comment by clarketm** [comment]
I created an issue upstream to track the work: https://github.com/kubernetes/test-infra/issues/16487
