### ISSUE TITLE
Add secret for grafana credentials

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2441]
For https://github.com/istio/istio/issues/21541 we will need grafana credentials in the cluster. This will be used by the release builder.

I am not sure if there is a standard practice for how we handle these secrets in the cluster?

**Comment by howardjohn** [comment]
This is not particularly urgent, by the way, timeline for this is 1.6 which is released in 3 months. I still need to write all the code to handle this anyways

**Comment by clarketm** [comment]
There is currently an issue tracking the proposal for a standard, declarative, secret manager tool/service (https://github.com/kubernetes/test-infra/issues/14049). 

The _current_ practice is to backup the secret value in an external data store, manually upload the value as a Kubernetes secret in the cluster(s), and _optionally_ create a Prow preset for convenience (if applicable).

**Comment by howardjohn** [comment]
In this specific case we only need it on one job so preset is probably not really needed

**Comment by clarketm** [comment]
Created secret `grafana-token` with key `token` in `test-pods` namespace of `istio-prow-build` cluster.

**Comment by howardjohn** [comment]
Thanks!
