### ISSUE TITLE
Update prow cluster version

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2451]
Right now we are on 1.13.12-gke.25 which is pretty old. We may want to look into upgrading to 1.15 at some point.

note: I don't know of any particular reasons 1.15 would be better other than its the recommended version now

**Comment by clarketm** [comment]
All Prow clusters are currently configured to [auto-upgrade](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades). If we want to continue to auto-upgrade but use a newer version of Kubernetes, then we can leverage [release channels](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels), likely the [regular](https://cloud.google.com/kubernetes-engine/docs/release-notes-regular) channel which is recommended for _production-quality_ clusters needing (or wanting) the latest k8s features while still covered by [GKE SLA](https://cloud.google.com/kubernetes-engine/sla). The current upgrade channel is **no channel** (as our clusters predate this feature) which follows [this upgrade logic](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades#auto-upgrade-version-selection), hence the older version.

Apparently, [release channels](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels) cannot be enabled for [existing clusters](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#existing_clusters).

**Comment by clarketm** [comment]
All prow clusters upgraded to `1.15.9-gke.22`.
