### ISSUE TITLE
Investigate Terraform as an alternative to provision/deploy K8s infrastructure.

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2460]
https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html

> Terraform could also be useful for the provisioning of Istio's other GCP resources (e.g. https://github.com/kubernetes/test-infra/pull/14550).

**Comment by howardjohn** [comment]
We are doing this now https://github.com/istio/test-infra/tree/master/infra
