### ISSUE TITLE
Add automator job for updating build tools tag in istio/common-files

### ISSUE THREAD

**Issue by clarketm** [istio/test-infra#2469]
Add automator job for updating build tools tag in [`istio/common-files`](https://github.com/istio/common-files/) (i.e. https://github.com/istio/common-files/pull/202)

While a **postsubmit** would be ideal, without strong pipeline support in Prow this is needlessly complex. There will be a race between the image build/push (i.e. `containers_tools_postsubmit`) and the availability of the image (also, the job could fail). Furthermore, the image tag is *dynamic* and computed as a timestamp at runtime. 

As an alternative, a daily **periodic** to query *gcr.io* for latest image tag for the branch (i.e. `$branch-latest`), then grab the corresponding timestamped tag for that image (e.g. `$branch-$date`) can be employed.

Another alternative is to use a tekton pipeline and combine this with the `containers_tools_postsubmit` although support in Prow is limited.

**e.g.**
```shell
$ gcloud container images list-tags gcr.io/istio-testing/build-tools  \
--filter="tags:master-latest" \
| grep -Pom1 'master-[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}'
```

**Comment by zhlsunshine** [comment]
Hi @brian-avery & @ericvn, shall we move this issue to 1.12?
