### ISSUE TITLE
Switch to e2 ubuntu nodes

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2627]
* e2 nodes are cheaper
* Ubunutu nodes allow ipv6 testing

**Comment by howardjohn** [comment]
No major deadline on this, ipv6 testing has just been on the backburner for a while

**Comment by howardjohn** [comment]
@clarketm any progress on this? I am happy to take this on if you are busy with other things

**Comment by howardjohn** [comment]
Is it ok if I move these over?

**Comment by clarketm** [comment]
> Is it ok if I move these over?

Sorry, I missed this. I will switch them over today off-peak for the build cluster(s).

**Comment by clarketm** [comment]
Updated all build cluster `test-pool`s to e2 Ubuntu nodes.
