### ISSUE TITLE
Autobump job is performing no operations

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2704]
The autobump job `ci-prow-autobump` was creating PRs to update Prow, but is no longer doing so.
Job on Prow: https://prow.istio.io/?job=ci-prow-autobump
Example log: https://prow.istio.io/log?job=ci-prow-autobump&id=1584

The script seems to claim that there is no change, but the upstream prow images are updating and have newer images that exist.

**Comment by chases2** [comment]
A recent change to bump.sh was made that did contain a bug:
https://github.com/kubernetes/test-infra/pull/17649

The bug fixed the order in which images are checked and the bump change is made. A fix was merged for this: https://github.com/kubernetes/test-infra/pull/17897

However, the fix doesn't explain why plank_deployment.yaml left the list of files-to-bump. Without this file, `autobump.sh` won't detect that a change actually occurred and won't do anything.
Previous Bump Example: https://prow.istio.io/view/gs/istio-prow/logs/ci-prow-autobump/1525
Broken Bump Example: https://prow.istio.io/view/gcs/istio-prow/logs/ci-prow-autobump/1583

**Comment by cjwagner** [comment]
It has been working recently.
/close
