### ISSUE TITLE
pull-test-infra-check-testgrid-config job is broken

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2708]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2707/pull-test-infra-check-testgrid-config/1386

Looks like the bazel version is transfigure image is not compatible. The image we use is      not pinned so maybe its stale? its `gcr.io/k8s-prow/transfigure`.

**Comment by chases2** [comment]
I'm certain this has to do with our [bazelversion](https://github.com/istio/test-infra/blob/master/.bazelversion): 0.29.1
 I suspect the solution has to do with using a bazel version that an infrastructure piece doesn't support anymore, but I won't be able to deal with this immediately.

/assign @fejta

**Comment by chases2** [comment]
/assign @clarketm 
Have you run into an issue like this before?

**Comment by howardjohn** [comment]
Any info on this? Travis has left Google and this is blocking our CI @chases2

**Comment by scottilee** [comment]
I don't know if this is helpful but based on https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/transfigure it looks like image is built here: https://github.com/kubernetes/test-infra/blob/9a939de10fa72af415eb1e628345b7d16c1f0be0/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L118-L143 -- looks like we'd just have to send a PR with a more recent version like `gcr.io/k8s-testimages/bazelbuild:v20200609-e7bfd25-test-infra`?

**Comment by fejta** [comment]
FYI the latest image should be working again
