### ISSUE TITLE
What is "Automator" ?

### ISSUE THREAD

**Issue by maximveksler** [istio/test-infra#2798]
Hello,

I see istio has interesting automation going on which updates the docker versions after a successful build. Could someone please offer some info/references to how it's configured and where I can learn more about it?

**Comment by howardjohn** [comment]
Hey @maximveksler, the source for this is here: https://github.com/istio/test-infra/tree/master/tools/automator. For the various jobs that use it, you can look in `prow/cluster/jobs/` (run a grep for automator)
