### ISSUE TITLE
CPU leak in prow

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2864]
Our never ending problem... node with no jobs gets up to 80%+ resting CPU, all jobs scheduled start being flaky

![2020-07-08_07-56-06](https://user-images.githubusercontent.com/623453/89658519-81e7f800-d883-11ea-8020-d97f494abccb.png)

I don't really know how to fix this. For now just rebooting the nodes

**Comment by howardjohn** [comment]
Previous context https://github.com/istio/test-infra/issues/1988

**Comment by fejta** [comment]
/assign @cjwagner @chaodaiG 

Is this still a thing?

**Comment by cjwagner** [comment]
Im not familiar with this problem. Based on the linked issue this sounds like a docker resource leak in Istio's ProwJobs rather than a CPU leak in Prow's service components.

@howardjohn was this observed in Istio's default build cluster or somewhere else? Has this been problematic recently?

**Comment by listx** [comment]
@howardjohn ping?

**Comment by howardjohn** [comment]
I don't think this has been a problem anymore. I don't actually know that its 'fixed', but our nodes never last long enough to leak since we have autoscaling now.
