### ISSUE TITLE
boskos dependent jobs fail due to unable to get boskos resources

### ISSUE THREAD

**Issue by carolynhu** [istio/test-infra#2880]
- upgrade/downgrade: https://prow.istio.io/view/gs/istio-prow/logs/istio-upgrade-using-istioctl-1.6_latest-1.7_latest/27
- perf: https://storage.googleapis.com/istio-prow/logs/daily-fortio-performance-benchmark-release-1.7/27/build-log.txt

**Comment by chizhg** [comment]
Should have been fixed.
