### ISSUE TITLE
Reduce prow webhook alert

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2922]
istio often goes >5m without a hook
/assign
/kind oncall-hotlist

**Comment by chaodaiG** [comment]
This was fixed, istio prow webhook alert is not set at 30 minutes: https://github.com/istio/test-infra/blob/35117c2dcc41623f732dc2f9ecc0e1e82fbd40f2/prow/cluster/monitoring/mixins/lib/config.libsonnet#L50

/close
