### ISSUE TITLE
Enable RBAC for prow

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#2930]

**Comment by chaodaiG** [comment]
@fejta , can you add more description here? I'm seeing some prow components already using RBAC, for example crier: https://github.com/istio/test-infra/blob/master/prow/cluster/crier_rbac.yaml

**Comment by fejta** [comment]
Then maybe it is already fixed? I no longer remember the details.

**Comment by chaodaiG** [comment]
ah. right, I fixed it in https://github.com/istio/test-infra/pull/3277, sorry forgot to close this bug
