### ISSUE TITLE
Add automator for updating istio/envoy SHA in istio/proxy periodically

### ISSUE THREAD

**Issue by carolynhu** [istio/test-infra#2937]
As a prepare for easing the difficulties of regression detection. We need to frequently update istio/envoy SHA in istio/proxy so that once a regression is detected, we do not have to tracking back a few months of code changes.

**Comment by ericvn** [comment]
Note https://github.com/istio/istio/issues/24586 is for an update in the release streams to update istio/proxy when istio/envoy changes. This doesn't work for `master` since we don't have a way to automate on the upstream repo.
