### ISSUE TITLE
Manage Prow GCP Infra as code

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#2953]
Currently, our cluster and other GCP config is managed manually via UI. This makes it hard to track changes, understand what is configured (especially for people without direct access!), and safely make changes.

We should have all of this managed with git-ops in this repo, ideally. Specifically, the following would be especially useful:

* GKE version
* Node pool sizes, configuration, etc
* In cluster configmaps and secrets - secrets would need to use something like SealedSecret of course
* All prow infra deployments/services - this is currently in the repo, should probably be well integrated with whatever we do here though.

**Comment by scottilee** [comment]
Related: https://github.com/istio/test-infra/issues/2460

**Comment by howardjohn** [comment]
@cjwagner checking in a long time later - is this something Kubernetes has done at all?

**Comment by cjwagner** [comment]
We manage all cluster resources with automation now (all prow deployments/services and secrets), but the infrastructure (GKE version, node pools) is not automatically managed or based on checked in config.

**Comment by howardjohn** [comment]
We are doing this now https://github.com/istio/test-infra/tree/master/infra
