### ISSUE TITLE
TestGrid upload failing

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2957]
https://k8s-testgrid.appspot.com/istio_test-infra_postsubmit#post-istio-test-infra-upload-testgrid-config

Validation is failing as a postsubmit, preventing TestGrid changes from updating from this repository:

```
could not apply prowjob annotations: couldn't find dashboard "istio_envoy_periodic" for job "update-proxy_envoy_periodic"
```
(from https://prow.k8s.io/view/gcs/istio-prow/logs/post-istio-test-infra-upload-testgrid-config/418)

**Comment by chases2** [comment]
The test to prevent this was disabled as part of triaging https://github.com/istio/test-infra/issues/2708, and wasn't re-enabled.

**Comment by fejta** [comment]
is this still happening Sean?
