### ISSUE TITLE
Migrate prow cluster to E2 nodes

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#3012]
Currently our build pools (for 16 core machines -  64 core ones are not supported in E2) are on E2 machines, but not the prow cluster in istio-testing. We should move these over.

**Comment by chizhg** [comment]
I have followed https://cloud.google.com/kubernetes-engine/docs/tutorials/migrating-node-pool to migrate the prow cluster in istio-testing to E2 machines.
