### ISSUE TITLE
Prow adds most test flags twice for pilot integration test run

### ISSUE THREAD

**Issue by Monkeyanator** [istio/test-infra#3014]
Looking through the build dump for a random pilot integration test run ([this one for reference](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/28336/integ-pilot-k8s-tests_istio/22981/build-log.txt)) I noticed some flags were getting added to the test command twice:

```
go test -p 1 -v -count=1 -tags=integ ./tests/integration/pilot/... -timeout 30m \
 --istio.test.ci --istio.test.pullpolicy=IfNotPresent --istio.test.kube.loadbalancer=false --istio.test.work_dir=/logs/artifacts --istio.test.hub=localhost:5000 --istio.test.tag=istio-testing --istio.test.kube.config=~/.kube/config --istio.test.ci --istio.test.pullpolicy=IfNotPresent --istio.test.kube.loadbalancer=false --istio.test.work_dir=/logs/artifacts --istio.test.hub=localhost:5000 --istio.test.tag=istio-testing --istio.test.kube.config=~/.kube/config --istio.test.select=-postsubmit,-flaky,-multicluster \
```

Looks like every flag but `--istio.test.select` shows up twice. Probably harmless but not sure if there's a case where these duplicated flags would disagree with each other.

**Comment by fejta** [comment]
a) prow starts the container with exactly the arguments you specify in the podspec
b) this configured command does not include go test


https://github.com/istio/test-infra/blob/72663ca0931c1fb52ca06a0c01fea4bd30d3dcb8/prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml#L321-L380
