### ISSUE TITLE
PolicyBot Auto Deploy job is failing

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/test-infra#3104]
Impact: Policybot is currently down, unable to label issues or respond to queries.

https://prow.istio.io/view/gs/istio-prow/logs/deploy-policybot_bots_postsubmit/1343992863075078144

**Comment by therealmitchconnors** [comment]
I recently rotated the secrets contained in test-pods/policybot, and the failing command references them, so there's a possibility I did something wrong.  However, I've been over them several times and they appear correct to me...

**Comment by chizhg** [comment]
It was because the value of the secret has a trailing `\n`, after removing it the job was able to pass. Now the dashboard is back to normal - https://eng.istio.io/maintainers?filter=active.
