### ISSUE TITLE
Bot Adds XS Label to PR with 0 changes

### ISSUE THREAD

**Issue by adiprerepa** [istio/test-infra#3179]
See https://github.com/istio/istio/pull/30676

I reverted a commit and the diff ended up being nothing, and the bot added the XS label.

**Comment by brian-avery** [comment]
What is the expected behavior here? No label?

**Comment by adiprerepa** [comment]
Yeah, no label because there technically isn't a size. If we still want to
include a lab, XS is probably appropriate.

**Comment by howardjohn** [comment]
I think its fine to always have a label
