### ISSUE TITLE
prow config generator: outdated prowjob struct

### ISSUE THREAD

**Issue by chaodaiG** [istio/test-infra#3210]
prow config generator relies on prowjob struct from k8s/test-infra, but it's pinned to https://github.com/istio/test-infra/blob/287c6e45a0a3d6a7def0059bd53c1dd4ee468db4/go.sum#L1124. This is potentially risky in considering istio prow is updated weekly with latest prow, there is a chance of diverging.

**Comment by chaodaiG** [comment]
CC @chizhg

**Comment by chizhg** [comment]
Fixed by https://github.com/istio/test-infra/pull/3452
