### ISSUE TITLE
Add cloud logging and tracing to prow node pool access scope

### ISSUE THREAD

**Issue by bianpengyuan** [istio/test-infra#3229]
We'd like to run Stackdriver telemetry test with real stackdriver backend: https://github.com/istio/istio/issues/29284 which needs prow node pool to have trace and log read access scope. Currently it only has the following ones:
```
Service Control   Enabled
Service Management   Read Only
Stackdriver Logging API   Write Only
Stackdriver Monitoring API   Full
Stackdriver Trace   Write Only
Storage   Read Only
```

cc @chizhg

**Comment by bianpengyuan** [comment]
google cloud doc for how to add access scope: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes It will need to temporarily stop the node and then restart. Not sure if there is an elegant or declarative way to set up prow node pool.

**Comment by chizhg** [comment]
Is https://pantheon.corp.google.com/kubernetes/nodepool/us-west1-a/prow/test-pool-ubuntu?folder=&organizationId=&project=istio-prow-build the node pool you meant?

**Comment by howardjohn** [comment]
I don't think we can depend on stackdriver for Istio presubmits. We made it a requirement long ago that the tests can rub hermetically on a local machine, which in retrospect was a major improvement over the old model in my opinion.

**Comment by bianpengyuan** [comment]
> Is https://pantheon.corp.google.com/kubernetes/nodepool/us-west1-a/prow/test-pool-ubuntu?folder=&organizationId=&project=istio-prow-build the node pool you meant?

Yep

> I don't think we can depend on stackdriver for Istio presubmits. We made it a requirement long ago that the tests can rub hermetically on a local machine, which in retrospect was a major improvement over the old model in my opinion.

I am only planning to run it at postsubmit on github. We can make it presubmit at internal repo.

**Comment by howardjohn** [comment]
ack.

Do we want to rely on the underlying node to happen to be running in gke? It seems like it may be more appropriate to use boskos to get us a dedicated cluster ? The fact we run prow jobs in gke (or in a pod at all) is meant to be an implementation detail

**Comment by bianpengyuan** [comment]
> Do we want to rely on the underlying node to happen to be running in gke?

Yeah that would be the easiest. If this is a concern, we can skip the test with real SD by checking if the test is running on GCP or not.

> It seems like it may be more appropriate to use boskos to get us a dedicated cluster?

Why would we need dedicated cluster? This works with KinD. See the experiment here: https://github.com/istio/istio/pull/31659. Metrics verification passes, but log fails due to access control issue.

**Comment by howardjohn** [comment]
It feels a bit like a leaky abstraction to rely on the outer node. But it's probably the more pragmatic option so if it's skipped automatically and not in presubmit it should be fine. Thanks for the info!

**Comment by bianpengyuan** [comment]
This has been fixed. Thanks @chizhg !
