### ISSUE TITLE
proxy build is broken. update build-tools-proxy image

### ISSUE THREAD

**Issue by lambdai** [istio/test-infra#3366]
The latest gcr.io/istio-testing/build-tools-proxy cannot build the proxy.

We probably need to upgrade the pip3/python3.

Any guide?

**Comment by lambdai** [comment]
https://github.com/istio/proxy/pull/3365


ERROR: An error occurred during the fetch of repository 'kafka_pip3':
   Traceback (most recent call last):
	File "/home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/rules_python/python/pip_install/pip_repository.bzl", line 63, column 13, in _pip_repository_impl
		fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (ERROR: Could not find a version that satisfies the requirement Jinja2==3.0.1 (from -r /home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/envoy/source/extensions/filters/network/kafka/requirements.txt (line 1)) (from versions: 2.0rc1, 2.0, 2.1, 2.1.1, 2.2, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.8, 2.8.1, 2.9, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6, 2.10, 2.10.1, 2.10.2, 2.10.3, 2.11.0, 2.11.1, 2.11.2, 2.11.3)
ERROR: No matching distribution found for Jinja2==3.0.1 (from -r /home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/envoy/source/extensions/filters/network/kafka/requirements.txt (line 1))

**Comment by howardjohn** [comment]
dockerfile in https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile

**Comment by howardjohn** [comment]
Are you sure you don't need an update to rules_python or some bazel component though? Not super familiar, just seems like it might be that instead of pip

**Comment by lambdai** [comment]
> dockerfile in https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile

Thanks!



> Are you sure you don't need an update to rules_python or some bazel component though? Not super familiar, just seems like it might be that instead of pip

Bazel is upgraded by the bazelisk and .bazel.
I suspect host python because the error message showes python3.5 and 3.5 is not hard coded specified by anything in bazel.
 rules_python probably fixes the proxy as well, I can give it a try.

**Comment by lambdai** [comment]
Fail to build on ubuntu:xenial

1. envoy requires jinja2 >= 3.0.1
2. pip requires at least v21.0 to install jinja2
3. pip21 requires > python3.5 because python3.5 is no longer supported
```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
```

ubuntu:xenial installs only python3.5

I manually tried this script to install python3.8 on ubuntu:xenial. It works. However, I am not sure if we want to introduce ppa in our build image.

Can we upgrade ubuntu?
Thought? @howardjohn

**Comment by howardjohn** [comment]
How come jinja requires a new pip? I would have thought the library version and pip version are unrelated, but python tooling is a bit of a mess...

The biggest issue with updating Ubuntu is, IIUC that also means we require all users to upgrade (for VMs).

Is it possible to build but in some sort of glibc compatibility mode so we don't use any bes glibc features?

**Comment by lambdai** [comment]
> How come jinja requires a new pip? I would have thought the library version and pip version are unrelated, but python tooling is a bit of a mess...

It seems a certain version of pip could support install a version range of a lib/module. Unfortunately, the highest pip3 20.3.4 cannot install the required jinjia2 3.0.1

> The biggest issue with updating Ubuntu is, IIUC that also means we require all users to upgrade (for VMs).

Yeah, glibc is the pain. We had to upgrade some other day, right?

**Comment by lambdai** [comment]
> Is it possible to build but in some sort of glibc compatibility mode so we don't use any bes glibc features?

That's interesting. I don't find any reliable guidance.

I am trying to copy python3.8 from python context as my last try

**Comment by lambdai** [comment]
python3.8 in focal doesn't work in xenial: glibc version mismatch

**Comment by lambdai** [comment]
build python3 on proxy build image work

**Comment by lambdai** [comment]
TODO: update bazel and llvm 

# broader dep
# apt-get install -y make build-essential libssl-dev zlib1g-dev \
       libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
       libncurses5-dev libncursesw5-dev xz-utils tk-dev

apt install zlib1g-dev libssl-dev

./configure --with-ensurepip=install

make -j 48
make install

ln -s  /usr/local/bin/python3 /usr/bin/python

**Comment by howardjohn** [comment]
is it possible to just statically link glibc and never have to deal with compatibility again?

**Comment by lambdai** [comment]
> is it possible to just statically link glibc and never have to deal with compatibility again?

I found [this](https://sourceware.org/glibc/wiki/FAQ#Even_statically_linked_programs_need_some_shared_libraries_which_is_not_acceptable_for_me.__What_can_I_do.3F). glibc static linking is technically possible but has downside at runtime in ubuntu xenial. Some lua script will trigger it for sure. I am afraid it's unlikely to switch to static glibc ever...
