### ISSUE TITLE
prow: when job running, link to prow/deck logs

### ISSUE THREAD

**Issue by nlandolfi** [istio/test-infra#344]
I propose that we customize the link posted with different Prow job statuses.

I have the following use case in mind:
```
...job starts...
plank posts to Github with the prow/deck logs link
...the job completes...
plank posts to Github with the gubernator job link. 
```

**Comment by nlandolfi** [comment]
At present, this depends upon https://github.com/kubernetes/test-infra/pull/3876 going to master in kubernetes/test-infra, and then us re-writing the [plank_url template in the prow/config.yaml](https://github.com/istio/test-infra/blob/master/prow/config.yaml#L3) to direct to https://prow.istio.io while the job is running, and to where it currently directs (Gubernator) after the job has completed.

**Comment by fejta** [comment]
/close

We are now linking to deck
