### ISSUE TITLE
Allow repo-wide code coverage requirement

### ISSUE THREAD

**Issue by lookuptable** [istio/test-infra#359]
Currently the `pkg_check` tool reads per-package code coverage requirement from a local file. If a package does not have an entry in the file, the code coverage requirement is effectively 0 (a.k.a. no tests are needed at all).

It would be better if we can set code coverage requirement for the whole repo, and uses the file to lower the coverage for certain package (e.g. a package only containing a main method).

cc @yutongz @sebastienvas

**Comment by sebastienvas** [comment]
That s a nice add on.
