### ISSUE TITLE
Reboot test cluster every so often

### ISSUE THREAD

**Issue by kyessenov** [istio/test-infra#360]
PRs might leave behind stale resources in the cluster due to accidents or developer error.
We should try to reset the cluster every few hours / daily.

**Comment by ldemailly** [comment]
^reboot^reset

**Comment by sebastienvas** [comment]
I think the way to go about this is to find what tests are leaving behind and clean that up.

This is really impractical. There is no way for me to have a lock on the cluster once test are running. This will be resolved once the cluster pool is implemented.

Closing this as won't fix.
