### ISSUE TITLE
Create a debian repository for istio released debian packages

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#368]
As part of istio release 0.2, we ll be publishing debian packages. Those package will be available for people to download and install manually, but we want to create a repository available to the public.

For short term we can use Google internal tools to do that, but this means that only Googler will be able to update the repo with release packages.

An alternative would be to create and maintain our own repo until we can push it to official debian repos. If creating our own repo, we need to be able to publish debian artifacts in a central location and have the repo make it available.

**Comment by sebastienvas** [comment]
Downgrading to P2, @smawson said we could document manual install for the debian packages for 0.2. Also k8s is also trying to do something like this
https://github.com/kubernetes/sig-release/issues/10

**Comment by howardjohn** [comment]
I don't think we have any plans to do this any longer
