### ISSUE TITLE
Migrate stable-artifacts Jenkins jobs to Cloud Builder

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#380]
Mixer: https://github.com/istio/mixer/blob/master/Jenkinsfile#L99
Pilot: https://github.com/istio/pilot/blob/master/Jenkinsfile#L115
Auth: https://github.com/istio/auth/blob/master/Jenkinsfile#L110

Note that we need to use KMS for pushing artifact to docker hub. We currently have an account defined.

**Comment by rvkubiak** [comment]
PRs sent to add cloud builder configs for Auth, Mixer, and Pilot.

istio/pilot#1096
istio/auth#235
istio/mixer#1123

**Comment by rvkubiak** [comment]
PR for build container: istio/test-infra#405
