### ISSUE TITLE
Enable optimized build for release 

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#381]
We need to double check that bazel build are done using -c opt for release.

**Comment by sebastienvas** [comment]
@ldemailly please assign it back to me once we have reached consensus on this.

**Comment by ldemailly** [comment]
looks like we need to make the images even if the initial default may or may not be to use them:
https://github.com/istio/istio/issues/426#issuecomment-323190935

ps: I can't change assignments in this repo (can you change that too?)

**Comment by sebastienvas** [comment]
closing this as this is a duplicate.
