### ISSUE TITLE
Prow failed to create _bazel_bootstrap dir

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#396]
In some case, prow failed to create the directory '/home/bootstrap/.cache/bazel/_bazel_bootstrap' which skip all tests and exit without error.

`W0818 21:11:19.327] INFO: $TEST_TMPDIR defined: output root default is '/home/bootstrap/.cache/bazel'.
W0818 21:11:19.327] Error: mkdir('/home/bootstrap/.cache/bazel/_bazel_bootstrap'): (error: 13): Permission denied`

**Comment by nlandolfi** [comment]
:( I saw this once or twice -- I am not positive of the cause. The one theory I had was that it might have something to do with the hostport trick we use...

**Comment by yutongz** [comment]
Hi Nick, glad to hear from you! Yes we have the same guess. After we started to run multiple tests on different environment combinations, this issue pops up more than it did before. Currently we increased node number of testing clusters and things are getting better.

**Comment by ldemailly** [comment]
for instance: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/592/istio-presubmit/412/

which script exactly generates that error message ? can it ls -l on error (or always) so we know why is there a permission denied

**Comment by ldemailly** [comment]
kuat / andra suggested to look into volume claim as a way to ensure assignment of volume

https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolumeclaim

**Comment by sebastienvas** [comment]
I looked at volume claim before, but this is not what we need unless we implement some kind of pool to recycle PVs. Using a volume claim will force us to use PVs, and therefore we would have to create multiple volume claims and then force jobs to use a given volume claim.

The way we do this now, is that we a use the host mount point and once a pod is started we stick to a node port which should prevent other pods from being scheduled, but apparently that does not work.

@spxtr the pods still starts and fails, I think it should be rescheduled in that case right ?

**Comment by spxtr** [comment]
The only time we've seen something similar was when we forgot to specify the HostPort for some of our jobs. Then we got a confusing message saying that the bazel server was shutting down when another job scheduled on the same node. That doesn't sound quite like what you're seeing here.

**Comment by sebastienvas** [comment]
Yeah I double checked, every pod mounting the cache also set the hostPort. One other different is that we run as a bootstrap user, instead of running with root.

**Comment by ldemailly** [comment]
we can also look into sharing the cache out of pod : 
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md

**Comment by sebastienvas** [comment]
We had hazelcast setup before, it added flakiness to our builds, but that's only the build cache. The cache we care about is downloading all the dependencies, which this does not do. I can disable the cache right now, it will probably at least 5 mn to all the jobs.

**Comment by sebastienvas** [comment]
Marking as fixed. Let's reopen if we see this again.

**Comment by ldemailly** [comment]
awesome, thanks for digging and finding one(hopefully "the") issue !
