### ISSUE TITLE
apparently bogus Submit Queue Required Github CI test is not green: prow/istio-presubmit.sh 

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#406]
Seems like the submit queue status is always stuck on waiting to be green even when it merges the PR anyway

example PR : https://github.com/istio/istio/pull/591

![screen shot 2017-08-22 at 4 19 30 pm](https://user-images.githubusercontent.com/3664595/29591816-b51a257c-8755-11e7-9f86-26da02505f35.png)

cc @sebastienvas cc @yutongz

**Comment by sebastienvas** [comment]
The submit queue does merge like it should, it just does not update the check status. @yutongz, could you please create an issue on kubernetes/test-infra and close this one ?

**Comment by yutongz** [comment]
I fixed it
