### ISSUE TITLE
bot shouldn't re trigger a test when it was already green/ready to merge

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#410]
https://github.com/istio/pilot/pull/1098
was briefly ready to merge and then the bot issues unnecessary
"/test all [submit-queue is verifying that this PR is safe to merge]"
which caused another set of tests to run for no reason I can find, delaying the merge

**Comment by sebastienvas** [comment]
Agreed I raised this issue before. Note that this is only happening when your PR is at the top the queue or that the queue has only one PR.

The reason this is happening is that submit queue has a different list of tests that github has. (Github was lagging behind when this was implemented)

There are 2 ways we can deal with this:
1. Change Submit Queue look at the github api and check for required tests and add a little optimization to not re-run the tests if PR is already in mergeable state.
2. Move github long required steps to be in the submit queue list only so there are only triggered once submit queue get around to test it. Which is the way k8s uses the submit queue.

We should document this in the k8s/test-infra issues.

**Comment by ldemailly** [comment]
this is still happening and slows down quite a lot (double test for no reason)

**Comment by yutongz** [comment]
Tide will solve this.

**Comment by fejta** [comment]
Now using tide, which has the best of both worlds (aka will use tests so long as they are current, does not require user to pull in new changes to PR)

/close
