### ISSUE TITLE
Disable bazel cache on postsubmit

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#427]
We should disable bazel cache on postsubmit to make sure we can build from scratch. Cache is here to make presubmit faster, but we have more time for postsubmit to

**Comment by ldemailly** [comment]
or if not postsubmit, on the nightly ?

**Comment by sebastienvas** [comment]
We don't have nightly just yet, while bazel cache should never be an issue, it seems to be, and we might want to file bug to bazel for this. 
Anyway today we need a signal to know when we need to clear the cache and I think postsubmit and nightly are good candidate.
