### ISSUE TITLE
strange "merge not something we can merge" git error on pre submit

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#428]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1121/pilot-presubmit/613/

I0828 19:48:53.884] Bootstrap pilot-presubmit...
I0828 19:48:53.884] Gubernator results at https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1121/pilot-presubmit/613
I0828 19:48:53.884] Root: /home/bootstrap/go/src
I0828 19:48:53.884] Checkout: /home/bootstrap/go/src/github.com/istio/pilot master:62369fe930f881b894f43e73f9f158da61cb662d,1121:b68464c8c546bd96168522bdc35bf1f222aef64f
I0828 19:48:53.884] Call:  git init github.com/istio/pilot
I0828 19:48:53.945] Initialized empty Git repository in /home/bootstrap/go/src/github.com/istio/pilot/.git/
I0828 19:48:53.945] process 72 exited with code 0 after 0.0m
I0828 19:48:53.945] Call:  git clean -dfx
I0828 19:48:53.947] process 73 exited with code 0 after 0.0m
I0828 19:48:53.948] Call:  git reset --hard
I0828 19:48:53.950] process 74 exited with code 0 after 0.0m
I0828 19:48:53.950] Call:  git config --local user.name 'K8S Bootstrap'
I0828 19:48:53.955] process 75 exited with code 0 after 0.0m
I0828 19:48:53.955] Call:  git config --local user.email k8s_bootstrap@localhost
I0828 19:48:53.957] process 76 exited with code 0 after 0.0m
I0828 19:48:53.957] Call:  git fetch --quiet --tags https://github.com/istio/pilot master +refs/pull/1121/head:refs/pr/1121
I0828 19:48:54.510] process 77 exited with code 0 after 0.0m
I0828 19:48:54.510] Call:  git checkout -B test 62369fe930f881b894f43e73f9f158da61cb662d
W0828 19:48:54.535] Switched to a new branch 'test'
I0828 19:48:54.535] process 89 exited with code 0 after 0.0m
I0828 19:48:54.535] Call:  git merge --no-ff -m 'Merge +refs/pull/1121/head:refs/pr/1121' b68464c8c546bd96168522bdc35bf1f222aef64f
W0828 19:48:54.539] merge: b68464c8c546bd96168522bdc35bf1f222aef64f - not something we can merge
E0828 19:48:54.539] Build failed
I0828 19:48:54.539] process 90 exited with code 1 after 0.0m
E0828 19:48:54.539] unexpected error
Traceback (most recent call last):
  File "./bootstrap.py", line 878, in bootstrap
    setup_root(call, args.root, repos, args.ssh, args.git_cache, args.clean)
  File "./bootstrap.py", line 793, in setup_root
    checkout(call, repo, branch, pull, ssh, git_cache, clean)
  File "./bootstrap.py", line 260, in checkout
    call(['git', 'merge', '--no-ff', '-m', 'Merge %s' % ref, head])
  File "./bootstrap.py", line 860, in <lambda>
    call = lambda *a, **kw: _call(end, *a, **kw)
  File "./bootstrap.py", line 148, in _call
    raise subprocess.CalledProcessError(code, cmd, lines)
CalledProcessError: Command '['git', 'merge', '--no-ff', '-m', 'Merge +refs/pull/1121/head:refs/pr/1121', 'b68464c8c546bd96168522bdc35bf1f222aef64f']' returned non-zero exit status 1

**Comment by ldemailly** [comment]
ping https://github.com/istio/pilot/pull/1121 is still mysteriously stuck/failing

**Comment by nlandolfi** [comment]
hmm looks like a merge conflict? not sure why

**Comment by ldemailly** [comment]
I've seen this sporadically but I guess it's not high pri
