### ISSUE TITLE
Prow should update pending and failed status to run_after_success jobs.

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#440]
Mungegithub merges the pr based on second round e2e and first round presubmit

presubmit: green
e2e: green
<--- mungegithub: /test all
presubmit: pending
e2e: green
---> presubmit succeeds
presubmit: green (second round)
e2e: green (first round)

Racing ----> mungegithub merges the pr (two green while they may not bases on same code)
            |
             ---> run_after_succeed rule triggers e2e (second round)

presubmit: green
e2e: failed !! 
--- But pr is already merged

**Comment by yutongz** [comment]
One example: https://github.com/istio/pilot/pull/1090

**Comment by yutongz** [comment]
/assign @yutongz
fyi @sebastienvas

**Comment by sebastienvas** [comment]
@spxtr - I think this is due to the fact that we are using run_after_sucess on PR, and that in that case, Prow should probably mark childs jobs as pending when parent is running. What do you think ?

**Comment by spxtr** [comment]
That makes some sense to me. It can be set to pending with a description of "waiting for parent job" or something. Tide will handle this case properly.

**Comment by sebastienvas** [comment]
I have a non working PR here:
https://github.com/sebastienvas/k8s-test-infra/pull/1

The test currently hangs, I wonder if is because I need to create the prow job, but then if I do it is going to execute it which is not what I want.

**Comment by sebastienvas** [comment]
https://github.com/kubernetes/test-infra/pull/4351

**Comment by yutongz** [comment]
fixed
