### ISSUE TITLE
Document release note process in common pages.

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#445]
We need to detail the job responsbilities of reviewer as every important change needs to have a review.
I think the doc should be in there:
https://github.com/istio/istio/blob/master/CONTRIBUTING.md

@geeknoid Is this location correct ? Where should we put the documentation about adding release notes to PR ?

**Comment by geeknoid** [comment]
Yes, the right place for that kind of guidance.

**Comment by yutongz** [comment]
/close
We don't use release-note tool any more.
