### ISSUE TITLE
upload unittest logs

### ISSUE THREAD

**Issue by xiaolanz** [istio/test-infra#456]
I need to access local test logs run in presubmit to debug test failures.  Sometimes, unittest only fails at forge due to environment setup issue. 

W0906 21:45:11.381] FAIL: //pkg/platform/kube/crd:go_default_test (see /home/bootstrap/.cache/bazel/_bazel_bootstrap/d0f8e56b36f4f8161921504f3472e09b/execroot/com_github_istio_broker/bazel-out/local-fastbuild/testlogs/pkg/platform/kube/crd/go_default_test/test.log)
W0906 21:45:11.387] ____Elapsed time: 35.165s, Critical Path: 29.14s
I0906 21:45:11.394] //pkg/model/config:go_default_test                                       PASSED in 1.1s
I0906 21:45:11.394] //pkg/version:go_default_test                                            PASSED in 1.1s
I0906 21:45:11.394] //pkg/version:small_tests                                                PASSED in 1.1s
I0906 21:45:11.394] //pkg/platform/kube/crd:go_default_test                                  FAILED in 0.8s

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_broker/21/broker-presubmit/7/

**Comment by yutongz** [comment]
It failed on my machine too, so good guess is you have something special setup on your developing environment.

```
FAIL: //pkg/platform/kube/crd:go_default_test (see /usr/local/google/home/yutongz/.cache/bazel/_bazel_yutongz/7616127569af5e5068f698bc695889df/execroot/com_github_istio_broker/bazel-out/local-fastbuild/testlogs/pkg/platform/kube/crd/go_default_test/test.log)
INFO: Elapsed time: 70.324s, Critical Path: 19.30s
INFO: Build completed, 1 test FAILED, 615 total actions
//pkg/model/config:go_default_test                                       PASSED in 0.1s
//pkg/version:go_default_test                                            PASSED in 0.1s
//pkg/version:small_tests                                                PASSED in 0.1s
//pkg/platform/kube/crd:go_default_test                                  FAILED in 0.7s
```

**Comment by xiaolanz** [comment]
For this particular case, we found it was the kubeconfig issue. But in general, it would be nice to provide the logs.

**Comment by yutongz** [comment]
I agree. Let's see if we will have increasing number of this issue happen.

**Comment by xiaolanz** [comment]
There is bazel arg to show glog logs and files:

bazel test --features=race  --test_arg=--logtostderr --test_arg=--v=3 --test_arg=-test.v=true --test_output=all //...

Here is the log example: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_broker/21/broker-presubmit/16/

**Comment by sakshigoel12** [comment]
@sebastienvas is this for 0.3?

**Comment by sebastienvas** [comment]
as discussed people can just add  --test_output=all to their bazel test scripts in prow and they ll have the right logs.
