### ISSUE TITLE
skip_report doesn't skip

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#467]
Thought I added skip_report in [pilot-coverage](https://github.com/istio/test-infra/blob/master/prow/config.yaml#L614), it still reports back to github.

**Comment by sebastienvas** [comment]
Do you have an example in which case it does it. Is it only when the job is marked as pending, because parent changed ?

**Comment by sebastienvas** [comment]
that s probably a bug in the code I added.

**Comment by yutongz** [comment]
Might be.
From what I saw, there are two case:

- If parent job failed, your code updates child job to failed [pilot/1197](https://github.com/istio/pilot/pull/1197):
![image](https://user-images.githubusercontent.com/25786429/30197188-094be3fc-941b-11e7-9825-64a49b5d9999.png)

- If parent job succeeded, the child job sticks on pending, even it already failed [pilot/1199](https://github.com/istio/pilot/pull/1199):
![image](https://user-images.githubusercontent.com/25786429/30197233-5fe43aac-941b-11e7-89d4-6482b6fc7900.png)
![image](https://user-images.githubusercontent.com/25786429/30197240-6acb7142-941b-11e7-964c-3bf7fbf5babf.png)

**Comment by sebastienvas** [comment]
Yes I introduced this I believe.
