### ISSUE TITLE
Split post submit and PR image push

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#475]
So we can clearly identify a random pr Sha vs post submit

But also so we can have lower retention on the random pr storage of images vs the good ones.

**Comment by sebastienvas** [comment]
is this still valid ?

**Comment by ldemailly** [comment]
well given our storage bill I would guess it is, no ?

**Comment by ldemailly** [comment]
I think @rkpagadala is looking at this

**Comment by hklai** [comment]
I think we can just purge old images irrespective to random PRs and post submit.
We care more about the release images, but not the images for testing.

**Comment by hklai** [comment]
We now have a job to purge images older than 7 days from GCR.
