### ISSUE TITLE
Periodic delete dep-update branches

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#478]
I noticed there are around 20 dep-update branches in istio/istio and two or three in pilot and mixer. We should have periodic job to delete this kind of branches whatever the reasons (maybe people manually close/merge those PRs).

**Comment by chxchx** [comment]
I see. The problem is that the bot only deletes branches in failed PRs. If a PR has been merged, then its branch remain. Will fix this soon.

**Comment by yutongz** [comment]
Fixed by https://github.com/istio/test-infra/pull/480

**Comment by chxchx** [comment]
Branches still dangle if PRs were closed by hand. Fix this in https://github.com/istio/test-infra/pull/524
