### ISSUE TITLE
Leaking GCP firewall rules when delete a cluster

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#517]
When we delete a cluster, for some reason, ingress firewall rule is not being delete properly.

Left firewall rules named like "k8s-1137b7f67aec1d91-node-http-hc" and "k8s-fw-a7536c92f946d11e78b1242010a8001d"

**Comment by yutongz** [comment]
We believe Mason should be able to solve/work around this issue. Need some monitoring, if we don't suffer this problem any more, we can close this.

/assign @sebastienvas @chxchx 

It's your call.

**Comment by chxchx** [comment]
Pretty sure mason fixes this since the resource distribution unit is now per-project and everything dies after a project is reclaimed. I am closing this but I am missing something Seb could chime in. Will also monitor this too.
