### ISSUE TITLE
release_note_collector creates wrong release notes against non-master branch.

### ISSUE THREAD

**Issue by ayj** [istio/test-infra#555]
`release_note_collector` creates wrong release notes against non-master branch. The following command generates `release-notes` file but entries sometimes reference changes against the master branch instead of the release branch.

```bash
bazel-bin/toolbox/release_note_collector/release_note_collector \ 
    --previous_release 0.2.7 \
    --current_release 0.2.9 \
    --repos istio,mixer,pilot,auth \
    --pr_link 
```

**Comment by yutongz** [comment]
fixed in https://github.com/istio/test-infra/pull/561 and https://github.com/istio/istio/pull/1205
