### ISSUE TITLE
Updating version in downloadIstioCandidate.sh during release should be configurable 

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#556]
As we discussed in https://github.com/istio/istio/pull/1191. The release tool should have a flag to decide if we need to update version in download-script in master branch.

**Comment by yutongz** [comment]
/assign @chxchx 
Do you want to work on this fix?

**Comment by chxchx** [comment]
The release process is being revamped and we are going to start pre-release on 0.3.* soon. It guess it is a P2 for now.
