### ISSUE TITLE
Get rid of bootstrap.py on prow-builder in favor of the golang version

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#579]
We currently have a fork of the [bootstrap.py](https://github.com/istio/test-infra/blob/master/docker/istio_builders/prow_builder/bootstrap/bootstrap.py) which support android repo tool. Since work was already in progress by k8s team to move from python to golang we did not bother contributing back the changes.

Repo tool might be of interest for the k8s team as well, we should contribute those back to the golang version.

Check with @BenTheElder

**Comment by BenTheElder** [comment]
cc @stevekuznetsov who is looking to upstream some alternate tooling from OpenShift

**Comment by stevekuznetsov** [comment]
I expect the tools we upstream would fix this

**Comment by sebastienvas** [comment]
@stevekuznetsov Can you give us more information about this ?

**Comment by stevekuznetsov** [comment]
@sebastienvas sure -- y'all should drop by the SIG Testing weekly meetings or stand-ups! We also had a break-out session on this one. Basically, we have a set of Go tools that do things like the following:

 - check out the correct version of repos
 - generate `started.json` and `finished.json`
 - upload files to GCS

We are aiming to update Prow to where the user will provide a `PodSpec` and Prow will decorate it to add:

 - an init container that will add these tools to a shared volume
 - an init container that will use the tools to do code checkouts
 - an init container to generate and upload `started.json`
 - a sidecar container that will monitor the test container and upload logs to GCS

This will allow for a user adding a new job to simply provide an image and entrypoint and assume that their entrypoint will run in the working directory  with the correct source code checked out. As the test runs logs and artifacts will be streamed up to the correct place in GCS and there will be no need to use `bootstrap.py` type wrappers explicitly in your test definition. We are hammering out details in [this design doc](https://docs.google.com/a/google.com/document/d/1-ApXgeMOv6m79c3R1cLi3_t_xN5XANE_7vwtB0yFHmM/edit?usp=sharing). Expect some PRs from me soon.

**Comment by fejta** [comment]
+1 to attending our sig-testing meeting! Also our slack. Love to hear how you are using prow and contribute your improvements upstream!

Here's info about where we hangout: https://github.com/kubernetes/community/tree/master/sig-testing

**Comment by fejta** [comment]
Use pod-utils, not bootstrap
/close
