### ISSUE TITLE
Auto merge only take effect in istio/istio master

### ISSUE THREAD

**Issue by yutongz** [istio/test-infra#581]
We need auto-merge only takes effect on master but not release-branches since we are not done migrating. Since mungegithub is not able to tell branches, the workaround would be add a fake test in only master branch and make it one of the required check in mungegithub config. This test works as a flag, showing this is master and pass check, but not for other branches.

**Comment by yutongz** [comment]
Flag test in istio/istio:master https://github.com/istio/istio/pull/1525

**Comment by yutongz** [comment]
Prow trigger this test: https://github.com/istio/test-infra/pull/580

**Comment by ldemailly** [comment]
how come it's not able to tell the branches ? can that be fixed or at least an issue filled upstream?

**Comment by yutongz** [comment]
TBH, I personally don't think that's a requirement for the daily use case. And k8s only has one branch "master". Even for us, it's just a temporary. It's not worth to do that.

**Comment by ldemailly** [comment]
We'll always have release- branches no ?

**Comment by yutongz** [comment]
Yes, we will, and they will need auto-merge as well. I meant the current situation is temporary, i.e. 
master: enable
release branches: disable

I think you are right, being able to select branches is nice to be a more general tool, but I think we(istio) at least don't need to worries "too much" for now. Please correct me if there is a use case I missed.
Compared to this, how to deal with a larger amount of PRs waiting to be merged in a big mono-repo is more important. Right? So can we let it go :)

**Comment by yutongz** [comment]
/close

We solved it :)
