### ISSUE TITLE
"recent runs across PRs" show old entries

### ISSUE THREAD

**Issue by jmuk** [istio/test-infra#598]
I got https://k8s-gubernator.appspot.com/builds/istio-prow/directory/istio-presubmit this link from the presubmit check page, which is said to be "recent runs across PRs". However, it shows runs around early August, doesn't look very recent.

**Comment by yutongz** [comment]
I think this is a bug OR it's because we didn't upgrate deck to match the new directory structure.
@sebastienvas

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/istio-prow/directory/istio-presubmit/latest-build.txt
I think something else is wrong, not gubernator.

**Comment by sebastienvas** [comment]
resolved
