### ISSUE TITLE
Need protoc version 3.5.0 on prow machine

### ISSUE THREAD

**Issue by douglas-reid** [istio/test-infra#649]
Now that we are not using bazel for proto compiling, we need protoc on the prow build machines. We require v3.5.0 (this will match version in WORKSPACEs).

cc: @costinm

**Comment by costinm** [comment]
Why not on the .circleci image ?


Costin

**Comment by douglas-reid** [comment]
It should be on circleci too.  protoc everywhere for everyone, that's my motto.
