### ISSUE TITLE
Evaluate migration to prow

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#65]
prow: https://github.com/kubernetes/test-infra/tree/master/prow

Currently we are using Jenkins, because some of the workflow are not supported by prow:
 - Fast Forwarding passing commit from master to stable
 - Allow to run Jobs in module B when a PR is created on module A

Let's work with spxtr@ to see if this is something we might do.

**Comment by sebastienvas** [comment]
Talked to k8s engprod about this. It seems that transition is possible however we would need to implement our own bootstrapper probably based on their https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py although we might not need as much features.

**Comment by nlandolfi** [comment]
possibly a dupe of https://github.com/istio/test-infra/issues/236

**Comment by nlandolfi** [comment]
In late May we evaluated options for alternative CIs. We did ultimately go with Prow, which now runs the majority of our build and test workload (this is essentially the result of my internship). Jobs statuses are reported on PRs. A dashboard of all jobs running is available at https://prow.istio.io
