### ISSUE TITLE
Githubctl should report a failure if tests fail to run.

### ISSUE THREAD

**Issue by silverdev** [istio/test-infra#660]
In the case of https://github.com/istio-releases/daily-release/pull/200 githubctl claimed all zero tests passed. It should have reported that none of the configured test ran. In this case the run was blocked due to a permissions error. It would be even better if Githubctl reported a permissions error but all I'm asking for is that githubctl fail if the test don't run regardless of reason.

**Comment by silverdev** [comment]
This happend again last night. This time it was that the web hook failed to trigger the tests. we need to fix it

**Comment by chxchx** [comment]
fixed in https://github.com/istio/test-infra/pull/666
