### ISSUE TITLE
gcsweb.istio.io needs https

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#675]
some of the problems people are having connecting are related to http/https I think

and anyway it would be a lot better to use https

see admin-sites/fortio for an example of how to do it

**Comment by ldemailly** [comment]
@hklai fixit target ?

**Comment by sebastienvas** [comment]
Fixed by https://github.com/istio/admin-sites/pull/60

**Comment by ldemailly** [comment]
awesome !! thx ! https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/ ftw
I updated
https://github.com/istio/istio/wiki/Daily-builds
accordingly
