### ISSUE TITLE
Fix codecov.io's "No coverage uploaded for pull request base" with Jenkins

### ISSUE THREAD

**Issue by ayj** [istio/test-infra#72]
Codecov.io is mostly working with Jenkins on istio.io/manager. We still need to generate coverage reports upon successful merge into the master branch so codecov.io can properly generate coverage % diff against master (see warning message below). I think we just need to re-run coverage report on post-submit/commit trigger.

> No coverage uploaded for pull request base (master@f3fdddb). Click here to learn what that means.

**Comment by sebastienvas** [comment]
I am wondering if it ll make more sense to have a git repo with all the scripts that we share instead of having them in istio testing. then we can use a git submodule for those on each repo. That way we can share best practices more easily.

**Comment by ayj** [comment]
Sounds reasonable assuming the individual repos share common structure, development, practices, etc. But not sure how that would affect this particular issue? I thought the "no coverage" error was because we aren't generating coverage report on merged commits to master via post-submit hook?

**Comment by sebastienvas** [comment]
For this issue I ll just create a shared method  to publish Code Coverage and will leave the /bin/codecov script.

**Comment by sebastienvas** [comment]
this was resolved with #85.
