### ISSUE TITLE
velodrome: can we add fortio in repo list

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#731]
thanks
(or how can I login and edit the dashboard myself ? or is it checked in here?)

**Comment by chxchx** [comment]
I think you need to make a PR to https://github.com/kubernetes/test-infra/blob/master/velodrome/config.yaml#L145 since the k8s people host the velodrome for us.

@yutongz probably knows more about this.

**Comment by ldemailly** [comment]
doing that now, thanks @chxchx !
