### ISSUE TITLE
Release 0.8, 1.0-snapshot, and master have incompatible set of test jobs

### ISSUE THREAD

**Issue by chxchx** [istio/test-infra#901]
Recent chances on prow config.yaml by adding new jobs and removing old ones will break other branches on istio that were forked off earlier than this change, since they do not have the corresponding scripts. The fundamental issue here is that test-infra and istio are two repos and branches on istio has no implications directly on test-infra. 

A quick fix would be to split `common_qual_branches` in prow config into two sets -- master and previous releases, bring back the old jobs, run the old set of jobs on previous release branches, and run the new jobs only on master. 

/cc @hklai @rkpagadala @sebastienvas

**Comment by hklai** [comment]
Yes. @sebastienvas  and I had been discussing and he is going to create different config files per branch.

**Comment by rkpagadala** [comment]
seperate config files per branch are already created
