### ISSUE TITLE
Unify modules contribution experience

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#91]
Jenkins libraries resources are very limited. It would be good to have a submodules with all checks (linter, codecov, docker, etc...) checked in such that we can update all modules at once.

Change would be implemented on the sumodules and then a PR to each module would be necessary to enable it, which will also include potential change to make the checks pass.

That way we could also call just one method that does all the checks, and user would still be able to run the checks from the repo they are working on. (Which is impossible with Jenkins pipeline library resource)

**Comment by ayj** [comment]
ref https://github.com/kubernetes/repo-infra

**Comment by yutongz** [comment]
Using subtree instead of submodule

**Comment by sebastienvas** [comment]
We got some push back from the team. We'll revisit this in beta once the script are stable.

**Comment by ldemailly** [comment]
@sebastienvas can you update the description to remove jenkins reference and add stuff from the closed issue
(rewording:)

We have a growing amount of boilerplate across repos (mixer/bin/* broker/bin/* pilot/bin/* proxy/script/* for example). It'd be great if we can consolidate. Perhaps we need to put all this stuff into a common repo and just include that common repo as a submodule in all the other repos?"

ie unify the makefiles, bazel_to_go, linters, formatters, etc across our repos

**Comment by kyessenov** [comment]
The scripts are not doing the same thing across the repos. So unifying them
requires getting consistent bazel build first. Mixer build is a lot more
involved with lots of bazel hacks.

**Comment by sebastienvas** [comment]
Also we need to unify use of proto libraries.

**Comment by ldemailly** [comment]
can we update the summary ?

**Comment by sebastienvas** [comment]
There is one main repo now. closing this
