### ISSUE TITLE
Merge bot should not remove lgtm label on rebase or simple changes

### ISSUE THREAD

**Issue by hklai** [istio/test-infra#911]
For now, if anyone sends a new commit (even a one liner linter error fix), or rebase, the lgtm label is removed.

It is a burden to both the author (i.e. has to bug others other) and reviewers (have to monitor and lgtm again). 

It will be good if the bot can detect these changes and remove the lgtm label when there is substantial unreviewed changes.

**Comment by sebastienvas** [comment]
A one liner could break a lot of things, so the ask does not seem reasonable.

For PR to be merged by the bot, there is no need to rebase or merge. The only time a merge or a rebase is required is when there is a conflict which is a code change, and therefore require another review.

**Comment by sebastienvas** [comment]
The bot is designed for the community meaning everyone and we cannot trust that everyone will make the right thing, so we need to have checks in place to prevent bad things from coming in. I think there are much more chance of having abuse if we allow rebase and merge.

**Comment by hklai** [comment]
The ask here is to not remove lgtm label **always**.

If the tests are still passing after rebase, how should that matter and what additional risk are we talking about? Both the code rebased from and the changes in the PR have already been reviewed. 

And in case the test fails, the PR will need attention anyway.

**Comment by sebastienvas** [comment]
A rebase means rewriting history. A user could have updated all the tests to exit 0 same from a merge.

**Comment by hklai** [comment]
It can, but what matters is the delta of the PR is adding to the base.

Say if we capture the delta when the PR is LGTMed, and compare that to the delta after the PR is rebased/updated, we can use that information to decide whether the LGTM label should be removed.

i.e if the delta of deltas is greater than a threshold, remove the label. Otherwise, leave it.

**Comment by hklai** [comment]
This should hopefully be resolved by https://github.com/kubernetes/test-infra/pull/9820
