### ISSUE TITLE
Prow jobs getting aborted and re-fired

### ISSUE THREAD

**Issue by hklai** [istio/test-infra#915]
See screenshot
![srehzdezog7](https://user-images.githubusercontent.com/31747472/42119789-cf974b50-7bc4-11e8-9306-7a3b63b34f19.png)

The jobs are getting aborted and restarted.

According to Cole Wagner:

Based on the screenshot, multiple of the same job are being triggered simultaneously (or in quick succession). If Prow finds that multiple instances of a job are running against the same code it aborts all but the newest instance.

I have never seen jobs get triggered twice like that, but I would suspect that there are either duplicate jobs in the config or events are being handled multiple times.
Perhaps you accidentally enabled webhooks at both the org and repo level? (GitHub isn't smart enough to dedup these).

Not super critical but it is noisy.

**Comment by howardjohn** [comment]
no action can be done on this a year later I would guess
