### ISSUE TITLE
Evaluate the need for alpha cluster for running Istio unit tests

### ISSUE THREAD

**Issue by hklai** [istio/test-infra#916]
In the past Istio tests relied on some alpha features, but it should not be the case anymore.

If so, we should move away from using alpha clusters which get deleted every 30 days. Because of the automatic deletion, Istio test had been failing for almost 20 hours and many developers were blocked.

![7gdnhwgfvbc](https://user-images.githubusercontent.com/31747472/42119850-b774cfe2-7bc5-11e8-8b6d-58dacd06bb13.png)

And in case alpha clusters are needed, they should be renewed automatically to minimize outages.

**Comment by sebastienvas** [comment]
Also recreated the main clusters to not be alpha.
