### ISSUE TITLE
Prow not receiving webhook?

### ISSUE THREAD

**Issue by hklai** [istio/test-infra#929]
In the last two days I had seen multiple PRs that did not kick off Prow tests. 

When I went to prow, I didn't see any tests for those PRs, so it apparently never got the webhook requests. When I did manual "/retest", I was able to kick off these tests.

Example PRs:
https://github.com/istio/istio/pull/7195
https://github.com/istio/proxy/pull/1854

**Comment by stevekuznetsov** [comment]
Oh, whoops -- wrong `test-infra` ...

**Comment by stevekuznetsov** [comment]
@hklai @munnerz did you guys deploy the `tracer`? It's a great way to search through the Prow infra to find everything to do with a PR.

I think the GitHub outages might have hit you on these PRs?

**Comment by hklai** [comment]
@stevekuznetsov

Github outage might be the culprit, but I thought the outage was mainly on 16th but we saw these problems on 17th as well.

Also, it's interesting that no circle tests were affected.  Only prow tests did not run. 


FWIW, when I sampled the recent PRs, prow tests are getting started now so the urgency is not that high, but it'd be good to be able to root cause it and prevent it from happening again if possible.

**Comment by stevekuznetsov** [comment]
As mentioned, the tracer is the tool we use to aggregate logs from the Prow cluster and look to see what different components are doing in response to a specific PR. It would be necessary to see that to debug something like this

**Comment by hklai** [comment]
@sebastienvas did we deploy tracer?

**Comment by stevekuznetsov** [comment]
(or just dump all of the logs from `hook` for instance and grep for the GitHub issue event UUID)

**Comment by howardjohn** [comment]
no action can be done on this a year later I would guess
